#! /usr/bin/env node

import {Command} from 'commander';
import {access} from 'node:fs/promises';
import {basename} from 'node:path';
import {chmod} from 'node:fs/promises';
import {closeSync} from 'node:fs';
import {createConnection} from 'node:net';
import {createHash} from 'node:crypto';
import {dirname} from 'node:path';
import {existsSync} from 'node:fs';
import {homedir} from 'node:os';
import {get as httpGet} from 'node:http';
import {isAbsolute} from 'node:path';
import {join} from 'node:path';
import {lstat} from 'node:fs/promises';
import {mkdir} from 'node:fs/promises';
import {openSync} from 'node:fs';
import {platform} from 'node:os';
import {readFile} from 'node:fs/promises';
import {readdir} from 'node:fs/promises';
import {realpath} from 'node:fs/promises';
import {relative} from 'node:path';
import {resolve} from 'node:path';
import {sep} from 'node:path';
import {spawn} from 'node:child_process';
import {stat} from 'node:fs/promises';
import {userInfo} from 'node:os';
import {writeFile} from 'node:fs/promises';
import yaml from 'js-yaml';

const DEFAULT_HOST = '127.0.0.1';
const DEFAULT_PORT = 1933;
const DEFAULT_OPENVIKING_VERSION = '0.3.12';
const DEFAULT_ACCOUNT = 'local';
const DEFAULT_AGENT_ID = 'threadnote';
const OPENVIKING_PACKAGE_NAME = 'openviking[local-embed]';
const OPENVIKING_SERVER_COMMAND = 'openviking-server';
const OPENVIKING_MCP_NAME = 'threadnote';
const LAUNCHD_LABEL = 'io.threadnote.openviking';
const MAX_SECRET_MATCHES_TO_PRINT = 5;
const SHIM_MARKER = 'Generated by threadnote';
const USER_MANIFEST_NAME = 'seed-manifest.yaml';
const DEFAULT_SEED_PATTERNS = [
  'AGENTS.md',
  'CLAUDE.md',
  'README.md',
  'CONTRIBUTING.md',
  '.github/AGENTS.md',
  '.github/CLAUDE.md',
  '.github/pull_request_template.md',
  '.github/PULL_REQUEST_TEMPLATE.md',
  '.github/PULL_REQUEST_TEMPLATE/*.md',
  '.claude/commands/*.md',
  '.claude/skills/**/SKILL.md',
  '.claude/**/*.md',
  '.agents/**/*.md',
  'docs/**/*.md',
] as const;

type AgentClient = 'claude' | 'codex';
type ClaudeMcpScope = 'local' | 'project' | 'user';
type CommandStatus = 'fail' | 'ok' | 'warn';
type PackageManager = 'pip' | 'pipx' | 'uv';

interface RuntimeConfig {
  readonly account: string;
  readonly agentContextHome: string;
  readonly agentId: string;
  readonly host: string;
  readonly manifestPath: string;
  readonly openVikingVersion: string;
  readonly port: number;
  readonly user: string;
}

interface ProjectManifest {
  readonly name: string;
  readonly path: string;
  readonly seed: readonly string[];
  readonly uri: string;
}

interface SeedManifest {
  readonly futureMonorepo?: {
    readonly pathCandidates: readonly string[];
    readonly uri: string;
  };
  readonly projects: readonly ProjectManifest[];
  readonly version: number;
}

interface CommandResult {
  readonly exitCode: number;
  readonly stderr: string;
  readonly stdout: string;
}

interface DoctorCheck {
  readonly detail: string;
  readonly name: string;
  readonly status: CommandStatus;
}

interface SeedCandidate {
  readonly destinationUri: string;
  readonly filePath: string;
  readonly projectName: string;
  readonly relativePath: string;
}

interface SkillCandidate {
  readonly filePath: string;
  readonly hash: string;
  readonly source: string;
}

interface MappedCommand {
  readonly args: readonly string[];
  readonly cwd?: string;
  readonly executable: string;
}

interface InstallOptions {
  readonly dryRun?: boolean;
  readonly packageManager?: PackageManager;
  readonly repairInvalidConfigs?: boolean;
}

interface RepairOptions {
  readonly dryRun?: boolean;
  readonly mcp?: string;
  readonly packageManager?: PackageManager;
  readonly start?: boolean;
}

interface DoctorOptions {
  readonly dryRun?: boolean;
  readonly strict?: boolean;
}

interface StartOptions {
  readonly dryRun?: boolean;
  readonly foreground?: boolean;
  readonly launchd?: boolean;
}

interface SeedOptions {
  readonly dryRun?: boolean;
  readonly manifest?: string;
  readonly native?: boolean;
}

interface McpInstallOptions {
  readonly apply?: boolean;
  readonly bearerTokenEnvVar?: string;
  readonly name?: string;
  readonly nativeHttp?: boolean;
  readonly scope?: ClaudeMcpScope;
  readonly url?: string;
}

interface RememberOptions {
  readonly dryRun?: boolean;
  readonly sourceAgentClient?: string;
  readonly stdin?: boolean;
  readonly text?: string;
}

interface RecallOptions {
  readonly dryRun?: boolean;
  readonly inferScope?: boolean;
  readonly nodeLimit?: string;
  readonly query: string;
  readonly uri?: string;
}

interface ReadOptions {
  readonly dryRun?: boolean;
}

interface ListOptions {
  readonly all?: boolean;
  readonly dryRun?: boolean;
  readonly nodeLimit?: string;
  readonly recursive?: boolean;
  readonly simple?: boolean;
}

interface HandoffOptions {
  readonly blockers?: string;
  readonly dryRun?: boolean;
  readonly nextStep?: string;
  readonly sourceAgentClient?: string;
  readonly task?: string;
  readonly tests?: string;
}

interface PackOptions {
  readonly dryRun?: boolean;
  readonly path?: string;
  readonly targetUri?: string;
  readonly uri?: string;
}

interface ForgetOptions {
  readonly dryRun?: boolean;
}

interface InitManifestOptions {
  readonly dryRun?: boolean;
  readonly path?: string;
  readonly replace?: boolean;
  readonly repo?: readonly string[];
}

interface JsonObject {
  readonly [key: string]: unknown;
}

async function main(): Promise<void> {
  const program = new Command();

  program
    .name('threadnote')
    .description('Threadnote shared context workflow for development agents')
    .showHelpAfterError()
    .option('--home <path>', 'Override THREADNOTE_HOME for this invocation')
    .option('--manifest <path>', 'Override THREADNOTE_MANIFEST for this invocation')
    .option('--host <host>', 'OpenViking host', DEFAULT_HOST)
    .option('--port <port>', 'OpenViking port', parsePort, DEFAULT_PORT);

  program
    .command('doctor')
    .description('Check local prerequisites, config files, manifest shape, and server health')
    .option('--dry-run', 'Show checks without writing anything')
    .option('--strict', 'Exit non-zero if any check fails')
    .action(async (options: DoctorOptions) => {
      await runDoctor(getRuntimeConfig(program), options);
    });

  program
    .command('install')
    .description('Install OpenViking if missing and create local config files if absent')
    .option('--dry-run', 'Print the actions without making changes')
    .option('--package-manager <manager>', 'pipx, uv, or pip', parsePackageManager)
    .action(async (options: InstallOptions) => {
      await runInstall(getRuntimeConfig(program), options);
    });

  program
    .command('repair')
    .description('Repair local OpenViking install, config files, server health, shim, manifest, and MCP config')
    .option('--dry-run', 'Print the repair actions without making changes')
    .option(
      '--mcp <clients>',
      'MCP clients to repair: available, all, none, codex, claude, or comma-separated list',
      'available',
    )
    .option('--no-start', 'Do not start OpenViking if health is failing')
    .option('--package-manager <manager>', 'pipx, uv, or pip', parsePackageManager)
    .action(async (options: RepairOptions) => {
      await runRepair(getRuntimeConfig(program), options);
    });

  program
    .command('start')
    .description('Start the local OpenViking server')
    .option('--dry-run', 'Print the start command without running it')
    .option('--foreground', 'Run in the foreground instead of detaching')
    .option('--launchd', 'Install and start a macOS LaunchAgent')
    .action(async (options: StartOptions) => {
      await runStart(getRuntimeConfig(program), options);
    });

  program
    .command('stop')
    .description('Stop the local OpenViking server or LaunchAgent')
    .option('--dry-run', 'Print the stop actions without running them')
    .action(async (options: ForgetOptions) => {
      await runStop(getRuntimeConfig(program), options);
    });

  program
    .command('seed')
    .description('Seed curated context from the manifest; never indexes whole repos by default')
    .option('--dry-run', 'Print files and ov commands without importing')
    .option('--manifest <path>', 'Manifest path for this seed run')
    .action(async (options: SeedOptions) => {
      await runSeed(getRuntimeConfig(program, options.manifest), options);
    });

  program
    .command('init-manifest')
    .description('Create or update a per-developer seed manifest from one or more repo roots')
    .option('--dry-run', 'Print the manifest without writing it')
    .option('--path <path>', 'Manifest path; defaults to THREADNOTE_MANIFEST or ~/.openviking/seed-manifest.yaml')
    .option('--replace', 'Replace the manifest instead of merging with existing projects')
    .option('--repo <path>', 'Repo root to include; repeat for multiple repos', collectOption, [])
    .action(async (options: InitManifestOptions) => {
      await runInitManifest(getRuntimeConfig(program), options);
    });

  program
    .command('seed-skills')
    .description('Seed Codex, Claude, and repo-local SKILL.md files as a searchable catalog')
    .option('--dry-run', 'Print skill files and ov commands without importing')
    .option('--manifest <path>', 'Manifest path for repo-local skill discovery')
    .option('--native', 'Use native OpenViking skill ingestion; requires a working VLM config')
    .action(async (options: SeedOptions) => {
      await runSeedSkills(getRuntimeConfig(program, options.manifest), options);
    });

  program
    .command('mcp-install')
    .description('Install OpenViking MCP config for a supported agent')
    .argument('<agent>', 'codex or claude')
    .option('--apply', 'Actually modify the selected agent config')
    .option('--name <name>', 'MCP server name', OPENVIKING_MCP_NAME)
    .option('--native-http', 'Install OpenViking native HTTP MCP endpoint instead of the local stdio adapter')
    .option('--scope <scope>', 'Claude MCP config scope: user, local, or project', parseClaudeMcpScope, 'user')
    .option('--url <url>', 'OpenViking native HTTP MCP URL')
    .option('--bearer-token-env-var <name>', 'Environment variable containing the local API key')
    .action(async (agent: string, options: McpInstallOptions) => {
      await runMcpInstall(getRuntimeConfig(program), parseAgentClient(agent), options);
    });

  program
    .command('remember')
    .description('Store a durable engineering memory in OpenViking')
    .option('--dry-run', 'Print memory and ov command without storing')
    .option('--source-agent-client <name>', 'codex, claude, gemini, or another client name', 'codex')
    .option('--stdin', 'Read memory text from stdin')
    .option('--text <text>', 'Memory text to store')
    .action(async (options: RememberOptions) => {
      await runRemember(getRuntimeConfig(program), options);
    });

  program
    .command('recall')
    .description('Search shared OpenViking context')
    .requiredOption('--query <query>', 'Search query')
    .option('--dry-run', 'Print ov command without searching')
    .option('-n, --node-limit <count>', 'Maximum number of search results')
    .option('--no-infer-scope', 'Disable query-based scope inference')
    .option('--uri <uri>', 'Restrict search to a viking:// URI')
    .action(async (options: RecallOptions) => {
      await runRecall(getRuntimeConfig(program), options);
    });

  program
    .command('read')
    .description('Read a viking:// URI returned by recall or list')
    .argument('<uri>', 'viking:// URI to read')
    .option('--dry-run', 'Print ov command without reading')
    .action(async (uri: string, options: ReadOptions) => {
      await runRead(getRuntimeConfig(program), uri, options);
    });

  program
    .command('list')
    .alias('ls')
    .description('List a viking:// directory')
    .argument('[uri]', 'viking:// URI to list', 'viking://')
    .option('-a, --all', 'Show hidden files such as .abstract.md and .overview.md')
    .option('--dry-run', 'Print ov command without listing')
    .option('-n, --node-limit <count>', 'Maximum number of nodes to list')
    .option('-r, --recursive', 'List subdirectories recursively')
    .option('-s, --simple', 'Print only paths')
    .action(async (uri: string, options: ListOptions) => {
      await runList(getRuntimeConfig(program), uri, options);
    });

  program
    .command('handoff')
    .description('Capture current repo state as a durable cross-agent handoff memory')
    .option('--blockers <text>', 'Known blockers')
    .option('--dry-run', 'Print handoff without storing')
    .option('--next-step <text>', 'Suggested next step')
    .option('--source-agent-client <name>', 'codex, claude, gemini, or another client name', 'codex')
    .option('--task <text>', 'Current task summary')
    .option('--tests <text>', 'Tests or checks run')
    .action(async (options: HandoffOptions) => {
      await runHandoff(getRuntimeConfig(program), options);
    });

  program
    .command('forget')
    .description('Remove a viking:// URI from local OpenViking context')
    .argument('<uri>', 'viking:// URI to remove')
    .option('--dry-run', 'Print ov command without deleting')
    .action(async (uri: string, options: ForgetOptions) => {
      await runForget(getRuntimeConfig(program), uri, options);
    });

  program
    .command('export-pack')
    .description('Export local OpenViking context to an .ovpack')
    .option('--dry-run', 'Print ov command without exporting')
    .option('--path <path>', 'Output .ovpack path')
    .option('--uri <uri>', 'Source viking:// URI to export', 'viking://')
    .action(async (options: PackOptions) => {
      await runExportPack(getRuntimeConfig(program), options);
    });

  program
    .command('import-pack')
    .description('Import an .ovpack into local OpenViking context')
    .requiredOption('--path <path>', 'Input .ovpack path')
    .option('--dry-run', 'Print ov command without importing')
    .option('--target-uri <uri>', 'Target parent viking:// URI', 'viking://')
    .action(async (options: PackOptions) => {
      await runImportPack(getRuntimeConfig(program), options);
    });

  await program.parseAsync(process.argv);
}

function getRuntimeConfig(program: Command, manifestOverride?: string): RuntimeConfig {
  const options = program.opts<{
    readonly home?: string;
    readonly host?: string;
    readonly manifest?: string;
    readonly port?: number;
  }>();
  const threadnoteHome = expandPath(options.home ?? process.env.THREADNOTE_HOME ?? '~/.openviking');
  const manifestPath = expandPath(
    manifestOverride ?? options.manifest ?? process.env.THREADNOTE_MANIFEST ?? defaultManifestPath(threadnoteHome),
  );
  return {
    account: process.env.THREADNOTE_ACCOUNT ?? DEFAULT_ACCOUNT,
    agentContextHome: threadnoteHome,
    agentId: process.env.THREADNOTE_AGENT_ID ?? DEFAULT_AGENT_ID,
    host: options.host ?? process.env.THREADNOTE_HOST ?? DEFAULT_HOST,
    manifestPath,
    openVikingVersion: process.env.THREADNOTE_OPENVIKING_VERSION ?? DEFAULT_OPENVIKING_VERSION,
    port: options.port ?? parsePort(process.env.THREADNOTE_PORT ?? String(DEFAULT_PORT)),
    user: process.env.THREADNOTE_USER ?? userInfo().username,
  };
}

function defaultManifestPath(agentContextHome: string): string {
  const userManifest = join(agentContextHome, USER_MANIFEST_NAME);
  return existsSync(userManifest) ? userManifest : builtInExampleManifestPath();
}

function builtInExampleManifestPath(): string {
  return join(toolRoot(), 'config', 'seed-manifest.example.yaml');
}

async function runDoctor(config: RuntimeConfig, options: DoctorOptions): Promise<void> {
  const checks: DoctorCheck[] = [];
  checks.push({name: 'mode', status: 'ok', detail: options.dryRun ? 'dry run; no writes' : 'read-only checks'});
  checks.push({name: 'platform', status: platform() === 'darwin' ? 'ok' : 'warn', detail: platform()});
  checks.push(await commandCheck('node', ['--version']));
  checks.push(await commandCheck('python3', ['--version']));
  checks.push(await commandCheck('openviking-server', ['--help']));
  checks.push(await firstCommandCheck('openviking cli', ['ov', 'openviking'], ['--help']));
  checks.push(await localEmbeddingCheck());
  checks.push(await firstCommandCheck('python installer', ['pipx', 'uv', 'pip3'], ['--version']));
  checks.push(await commandPresenceCheck('codex', ['--version']));
  checks.push(await commandPresenceCheck('claude', ['--version']));
  checks.push(await commandShimCheck());
  checks.push(await manifestCheck(config.manifestPath));
  checks.push(await fileCheck(join(toolRoot(), '.threadnoteignore'), 'ignore file'));
  checks.push(await fileCheck(join(toolRoot(), 'config', 'ov.conf.template.json'), 'server config template'));
  checks.push(await fileCheck(join(toolRoot(), 'config', 'ovcli.conf.template.json'), 'cli config template'));
  checks.push(await healthCheck(config));

  for (const check of checks) {
    console.log(`${formatStatus(check.status)} ${check.name}: ${check.detail}`);
  }

  const failureCount = checks.filter(check => check.status === 'fail').length;
  const warningCount = checks.filter(check => check.status === 'warn').length;
  console.log(`\nSummary: ${failureCount} failure(s), ${warningCount} warning(s)`);
  if (options.strict === true && failureCount > 0) {
    process.exitCode = 1;
  }
}

async function runInstall(config: RuntimeConfig, options: InstallOptions): Promise<void> {
  const repairInvalidConfigs = options.repairInvalidConfigs === true;
  await ensureDirectory(config.agentContextHome, options.dryRun === true);
  await ensureDirectory(join(config.agentContextHome, 'logs'), options.dryRun === true);
  await ensureDirectory(join(config.agentContextHome, 'redacted'), options.dryRun === true);
  await ensureDirectory(join(config.agentContextHome, 'mcp'), options.dryRun === true);
  await installCommandShim(options.dryRun === true);

  const serverPath = await findExecutable([OPENVIKING_SERVER_COMMAND]);
  if (serverPath) {
    console.log(`OpenViking server already installed: ${serverPath}`);
    if ((await hasLocalEmbeddingDependency(serverPath)) === false) {
      console.log('OpenViking local embedding extra is missing; repairing install.');
      const installCommand = await getInstallCommand(config, options.packageManager, true);
      await maybeRun(options.dryRun === true, installCommand.executable, installCommand.args);
    }
  } else {
    const installCommand = await getInstallCommand(config, options.packageManager, false);
    await maybeRun(options.dryRun === true, installCommand.executable, installCommand.args);
  }

  await writeTemplateIfMissing({
    config,
    destinationPath: join(config.agentContextHome, 'ov.conf'),
    dryRun: options.dryRun === true,
    shouldRepair: content =>
      shouldRepairOpenVikingConfig(content, config) ||
      (repairInvalidConfigs && parseJsonConfigObject(content) === undefined),
    templatePath: join(toolRoot(), 'config', 'ov.conf.template.json'),
  });
  await writeTemplateIfMissing({
    config,
    destinationPath: join(config.agentContextHome, 'ovcli.conf'),
    dryRun: options.dryRun === true,
    shouldRepair: content =>
      shouldRepairLegacyOvCliConfig(content) || (repairInvalidConfigs && parseJsonConfigObject(content) === undefined),
    templatePath: join(toolRoot(), 'config', 'ovcli.conf.template.json'),
  });

  console.log('Install complete. Run doctor, then start:');
  console.log('  threadnote doctor');
  console.log('  threadnote start');
}

async function runRepair(config: RuntimeConfig, options: RepairOptions): Promise<void> {
  const dryRun = options.dryRun === true;
  console.log('Repairing local OpenViking agent context from this checkout.');

  await runInstall(config, {dryRun, packageManager: options.packageManager, repairInvalidConfigs: true});
  await repairManifest(config, dryRun);

  if (options.start !== false) {
    await repairServerHealth(config, dryRun);
  } else {
    console.log('Skipping server health repair because --no-start was provided.');
  }

  const mcpClients = await resolveRepairMcpClients(options.mcp ?? 'available');
  if (mcpClients.length === 0) {
    console.log('Skipping MCP config repair.');
  } else {
    for (const client of mcpClients) {
      console.log(`Repairing ${client} MCP config for ${OPENVIKING_MCP_NAME}.`);
      await runMcpInstall(config, client, {apply: !dryRun, name: OPENVIKING_MCP_NAME});
    }
  }

  console.log('\nPost-repair doctor:');
  await runDoctor(config, {dryRun, strict: false});
}

async function repairManifest(config: RuntimeConfig, dryRun: boolean): Promise<void> {
  try {
    await readSeedManifest(config.manifestPath);
    console.log(`Manifest OK: ${config.manifestPath}`);
    return;
  } catch (err: unknown) {
    if (config.manifestPath === builtInExampleManifestPath()) {
      console.log(`WARN built-in manifest is not readable: ${errorMessage(err)}`);
      return;
    }
    console.log(`Manifest needs repair: ${config.manifestPath} (${errorMessage(err)})`);
  }

  let repoRoot: string;
  try {
    repoRoot = await resolveRepoRoot(getInvocationCwd());
  } catch (err: unknown) {
    console.log(`WARN cannot create replacement manifest from current directory: ${errorMessage(err)}`);
    return;
  }

  const project = projectManifestForRepo(repoRoot, []);
  const output = yaml.dump(
    {
      version: 1,
      projects: [
        {
          name: project.name,
          path: project.path,
          uri: project.uri,
          seed: [...project.seed],
        },
      ],
    },
    {lineWidth: 120, noRefs: true},
  );

  if (dryRun) {
    console.log(`# Would write replacement manifest: ${config.manifestPath}`);
    console.log(output.trimEnd());
    return;
  }

  await ensureDirectory(dirname(config.manifestPath), false);
  const currentContent = await readFileIfExists(config.manifestPath);
  if (currentContent !== undefined) {
    const backupPath = `${config.manifestPath}.legacy-${safeTimestamp()}`;
    await writeFile(backupPath, currentContent, {encoding: 'utf8', mode: 0o600});
    await chmod(backupPath, 0o600);
    console.log(`Backup: ${backupPath}`);
  }
  await writeFile(config.manifestPath, output, {encoding: 'utf8', mode: 0o600});
  await chmod(config.manifestPath, 0o600);
  console.log(`Wrote replacement manifest: ${config.manifestPath}`);
}

async function repairServerHealth(config: RuntimeConfig, dryRun: boolean): Promise<void> {
  const existingHealth = await readOpenVikingHealthIfAvailable(config, 800);
  if (existingHealth) {
    console.log(`OpenViking health OK at http://${config.host}:${config.port}/health`);
    return;
  }

  console.log(`OpenViking health is not responding at http://${config.host}:${config.port}/health; starting server.`);
  try {
    await runStart(config, {dryRun});
  } catch (err: unknown) {
    console.log(`WARN could not repair OpenViking health: ${errorMessage(err)}`);
  }
}

async function runStart(config: RuntimeConfig, options: StartOptions): Promise<void> {
  if (options.launchd === true) {
    await installLaunchAgent(config, options.dryRun === true);
    return;
  }

  const server =
    options.dryRun === true
      ? ((await findExecutable([OPENVIKING_SERVER_COMMAND])) ?? OPENVIKING_SERVER_COMMAND)
      : await requiredExecutable(OPENVIKING_SERVER_COMMAND);
  const args = openVikingServerArgs(config);
  if (options.dryRun === true) {
    console.log(formatShellCommand(server, args));
    return;
  }

  const existingHealth = await readOpenVikingHealthIfAvailable(config, 500);
  if (existingHealth) {
    console.log(`OpenViking is already healthy at http://${config.host}:${config.port}/health`);
    return;
  }
  if (await isTcpPortOpen(config.host, config.port, 500)) {
    throw new Error(
      `Port ${config.host}:${config.port} is already in use, but it is not a healthy OpenViking server. ` +
        'Set THREADNOTE_PORT or pass --port to use a different port.',
    );
  }

  await ensureDirectory(join(config.agentContextHome, 'logs'), false);
  if (options.foreground === true) {
    const result = await runInteractive(server, args);
    process.exitCode = result;
    return;
  }

  const logPath = join(config.agentContextHome, 'logs', 'server.log');
  const logFd = openSync(logPath, 'a');
  const child = spawnDetachedServerWithLog(server, args, logFd);
  child.unref();
  await writeFile(join(config.agentContextHome, 'openviking-server.pid'), `${child.pid}\n`, 'utf8');
  console.log(`Started OpenViking with pid ${child.pid}. Logs: ${logPath}`);
}

function spawnDetachedServerWithLog(server: string, args: readonly string[], logFd: number): ReturnType<typeof spawn> {
  try {
    return spawnDetachedServer(server, args, logFd);
  } finally {
    closeSync(logFd);
  }
}

function spawnDetachedServer(server: string, args: readonly string[], logFd: number): ReturnType<typeof spawn> {
  return spawn(server, args, {
    detached: true,
    stdio: ['ignore', logFd, logFd],
  });
}

async function runStop(config: RuntimeConfig, options: ForgetOptions): Promise<void> {
  const launchAgentPath = expandPath(`~/Library/LaunchAgents/${LAUNCHD_LABEL}.plist`);
  if (platform() === 'darwin') {
    await maybeRun(options.dryRun === true, 'launchctl', ['unload', launchAgentPath], {allowFailure: true});
  }

  const pidPath = join(config.agentContextHome, 'openviking-server.pid');
  const pidText = await readFileIfExists(pidPath);
  if (!pidText) {
    console.log('No pid file found for detached OpenViking server.');
    return;
  }
  const pid = Number(pidText.trim());
  if (!Number.isInteger(pid) || pid <= 0) {
    console.log(`Invalid pid file: ${pidPath}`);
    return;
  }
  if (options.dryRun === true) {
    console.log(`Would stop process ${pid}`);
    return;
  }
  try {
    process.kill(pid, 'SIGTERM');
    console.log(`Stopped process ${pid}`);
  } catch (err: unknown) {
    console.log(`Could not stop process ${pid}: ${errorMessage(err)}`);
  }
}

async function runSeed(config: RuntimeConfig, options: SeedOptions): Promise<void> {
  const manifest = await readSeedManifest(config.manifestPath);
  const ignorePatterns = await loadIgnorePatterns();
  const ov = await openVikingCliForMode(options.dryRun === true);
  let importedCount = 0;
  let skippedCount = 0;

  for (const project of manifest.projects) {
    const projectRoot = expandPath(project.path);
    if (!(await exists(projectRoot))) {
      console.log(`WARN project missing: ${project.name} (${projectRoot})`);
      continue;
    }

    const candidates = await collectSeedCandidates(project, projectRoot, ignorePatterns);
    for (const candidate of candidates) {
      const importPath = await prepareSeedFile(config, candidate, options.dryRun === true);
      if (!importPath) {
        skippedCount += 1;
        continue;
      }
      const args = withIdentity(config, ['add-resource', importPath, '--to', candidate.destinationUri, '--wait']);
      await maybeRun(options.dryRun === true, ov, args);
      importedCount += 1;
    }
  }

  console.log(`Seed complete: ${importedCount} candidate(s), ${skippedCount} skipped for safety.`);
}

async function runInitManifest(config: RuntimeConfig, options: InitManifestOptions): Promise<void> {
  const manifestPath = expandPath(
    options.path ?? process.env.THREADNOTE_MANIFEST ?? join(config.agentContextHome, USER_MANIFEST_NAME),
  );
  const repoInputs = options.repo && options.repo.length > 0 ? options.repo : [getInvocationCwd()];
  const existingManifest =
    options.replace === true || !(await exists(manifestPath)) ? undefined : await readSeedManifest(manifestPath);
  const existingProjects = existingManifest?.projects ?? [];
  const projects = [...existingProjects];
  const seen = new Set<string>();

  for (const project of existingProjects) {
    seen.add(await projectIdentity(project.path));
  }

  for (const repoInput of repoInputs) {
    const repoRoot = await resolveRepoRoot(repoInput);
    const identity = await projectIdentity(repoRoot);
    if (seen.has(identity)) {
      console.log(`Already in manifest: ${repoRoot}`);
      continue;
    }
    seen.add(identity);
    projects.push(projectManifestForRepo(repoRoot, projects));
  }

  const outputManifest: Record<string, unknown> = {
    version: 1,
    projects: projects.map(project => ({
      name: project.name,
      path: project.path,
      uri: project.uri,
      seed: [...project.seed],
    })),
  };
  if (existingManifest?.futureMonorepo) {
    const futureMonorepoKey = 'future_monorepo';
    const pathCandidatesKey = 'path_candidates';
    outputManifest[futureMonorepoKey] = {
      [pathCandidatesKey]: [...existingManifest.futureMonorepo.pathCandidates],
      uri: existingManifest.futureMonorepo.uri,
    };
  }
  const output = yaml.dump(outputManifest, {lineWidth: 120, noRefs: true});

  if (options.dryRun === true) {
    console.log(`# Would write ${manifestPath}`);
    console.log(output.trimEnd());
    return;
  }

  await ensureDirectory(dirname(manifestPath), false);
  await writeFile(manifestPath, output, {encoding: 'utf8', mode: 0o600});
  await chmod(manifestPath, 0o600);
  console.log(`Wrote manifest: ${manifestPath}`);
  console.log('Seed with:');
  console.log('  threadnote seed --dry-run');
  console.log('  threadnote seed');
}

async function runSeedSkills(config: RuntimeConfig, options: SeedOptions): Promise<void> {
  const ov = await openVikingCliForMode(options.dryRun === true);
  const skills = await collectSkillCandidates(config);
  const nativeMode = options.native === true;
  console.log(
    nativeMode
      ? 'Skill seed mode: native OpenViking skills. This requires a working VLM config.'
      : 'Skill seed mode: resource catalog. Use --native only after configuring a working VLM provider.',
  );
  for (const skill of skills) {
    console.log(`Skill ${skill.source}: ${skill.filePath}`);
    const args = nativeMode
      ? ['add-skill', skill.filePath, '--wait']
      : ['add-resource', skill.filePath, '--to', skillResourceUri(skill), '--wait'];
    await maybeRun(options.dryRun === true, ov, withIdentity(config, args));
  }
  console.log(`Skill seed complete: ${skills.length} unique skill(s).`);
}

async function resolveRepoRoot(repoInput: string): Promise<string> {
  const inputPath = expandPath(repoInput);
  if (!(await isDirectory(inputPath))) {
    throw new Error(`Repo path is not a directory: ${inputPath}`);
  }
  return (await gitValue(['rev-parse', '--show-toplevel'], inputPath)) ?? inputPath;
}

async function projectIdentity(path: string): Promise<string> {
  const expanded = expandPath(path);
  try {
    return await realpath(expanded);
  } catch (_err: unknown) {
    return expanded;
  }
}

function projectManifestForRepo(repoRoot: string, existingProjects: readonly ProjectManifest[]): ProjectManifest {
  const baseName = uriSegment(basename(repoRoot));
  const usedNames = new Set(existingProjects.map(project => project.name));
  const usedUris = new Set(existingProjects.map(project => project.uri));
  let name = baseName;
  let uri = `viking://resources/repos/${name}`;
  if (usedNames.has(name) || usedUris.has(uri)) {
    name = `${baseName}-${sha256(repoRoot).slice(0, 8)}`;
    uri = `viking://resources/repos/${name}`;
  }
  return {
    name,
    path: portablePath(repoRoot),
    seed: DEFAULT_SEED_PATTERNS,
    uri,
  };
}

async function runMcpInstall(config: RuntimeConfig, agent: AgentClient, options: McpInstallOptions): Promise<void> {
  const name = options.name ?? OPENVIKING_MCP_NAME;
  const url = options.url ?? `http://${config.host}:${config.port}/mcp`;
  const apply = options.apply === true;
  const nativeHttp = options.nativeHttp === true;
  const command = buildMcpInstallCommand(config, agent, name, {
    bearerTokenEnvVar: options.bearerTokenEnvVar,
    nativeHttp,
    scope: options.scope,
    url,
  });
  const removeCommand = buildMcpRemoveCommand(agent, name);

  if (nativeHttp) {
    const mcpStatus = await readHttpStatus(url, 1200);
    const unavailable = mcpStatus === undefined || mcpStatus === 404;
    if (unavailable && apply) {
      throw new Error(
        `OpenViking native MCP endpoint is not available at ${url}. ` +
          'Use the default stdio adapter, or install an OpenViking build that exposes /mcp.',
      );
    }
    if (unavailable) {
      console.log(`WARN OpenViking native MCP endpoint is not available at ${url}; default mcp-install uses stdio.`);
    }
  }

  if (!apply) {
    console.log('Dry run. Re-run with --apply to modify the selected agent config.');
    if (removeCommand.cwd || command.cwd) {
      console.log(`Command working directory: ${removeCommand.cwd ?? command.cwd}`);
    }
    console.log(formatShellCommand(removeCommand.executable, removeCommand.args));
    console.log(formatShellCommand(command.executable, command.args));
    printMcpSnippet(config, agent, name, {nativeHttp, scope: options.scope, url});
    return;
  }

  await maybeRun(false, removeCommand.executable, removeCommand.args, {
    allowFailure: true,
    cwd: removeCommand.cwd,
  });
  await maybeRun(false, command.executable, command.args, {cwd: command.cwd});
}

async function runRemember(config: RuntimeConfig, options: RememberOptions): Promise<void> {
  const text = await getInputText(options.text, options.stdin === true);
  if (!text.trim()) {
    throw new Error('Provide memory text with --text or --stdin.');
  }
  const memory = [
    'MEMORY',
    `source_agent_client: ${options.sourceAgentClient ?? 'codex'}`,
    `timestamp: ${new Date().toISOString()}`,
    '',
    text.trim(),
  ].join('\n');
  await storeMemory(config, memory, options.dryRun === true);
}

async function runRecall(config: RuntimeConfig, options: RecallOptions): Promise<void> {
  const ov = await openVikingCliForMode(options.dryRun === true);
  const inferredUri =
    options.uri ?? (options.inferScope === false ? undefined : await inferRecallUri(config, options.query));
  const args = ['search', options.query];
  if (inferredUri) {
    args.push('--uri', inferredUri);
    console.log(`Recall scope: ${inferredUri}`);
  }
  if (options.nodeLimit) {
    args.push('--node-limit', String(parsePositiveInteger(options.nodeLimit, 'node limit')));
  }
  await maybeRun(options.dryRun === true, ov, withIdentity(config, args));
}

async function runRead(config: RuntimeConfig, uri: string, options: ReadOptions): Promise<void> {
  assertVikingUri(uri);
  const ov = await openVikingCliForMode(options.dryRun === true);
  const result = await maybeRun(options.dryRun === true, ov, withIdentity(config, ['read', uri]));
  if (
    result &&
    result.stdout.includes('[Directory overview is not ready]') &&
    (uri.endsWith('/.overview.md') || uri.endsWith('/.abstract.md'))
  ) {
    const parentUri = parentVikingUri(uri);
    console.log('\nThis is a generated summary placeholder. To read the underlying content, inspect leaf nodes:');
    console.log(`  threadnote list ${parentUri} --all --recursive`);
  }
}

async function runList(config: RuntimeConfig, uri: string, options: ListOptions): Promise<void> {
  assertVikingUri(uri);
  const ov = await openVikingCliForMode(options.dryRun === true);
  const args = ['ls', uri];
  if (options.all === true) {
    args.push('--all');
  }
  if (options.recursive === true) {
    args.push('--recursive');
  }
  if (options.simple === true) {
    args.push('--simple');
  }
  if (options.nodeLimit) {
    args.push('--node-limit', String(parsePositiveInteger(options.nodeLimit, 'node limit')));
  }
  await maybeRun(options.dryRun === true, ov, withIdentity(config, args));
}

async function runHandoff(config: RuntimeConfig, options: HandoffOptions): Promise<void> {
  const handoff = await buildHandoff(options);
  await storeMemory(config, handoff, options.dryRun === true);
}

async function runForget(config: RuntimeConfig, uri: string, options: ForgetOptions): Promise<void> {
  assertVikingUri(uri);
  const ov = await openVikingCliForMode(options.dryRun === true);
  await maybeRun(options.dryRun === true, ov, withIdentity(config, ['rm', uri]));
}

async function runExportPack(config: RuntimeConfig, options: PackOptions): Promise<void> {
  const ov = await openVikingCliForMode(options.dryRun === true);
  const defaultPath = join(config.agentContextHome, `threadnote-${safeTimestamp()}.ovpack`);
  const outputPath = expandPath(options.path ?? defaultPath);
  await maybeRun(options.dryRun === true, ov, withIdentity(config, ['export', options.uri ?? 'viking://', outputPath]));
}

async function runImportPack(config: RuntimeConfig, options: PackOptions): Promise<void> {
  if (!options.path) {
    throw new Error('Provide --path for import-pack.');
  }
  const ov = await openVikingCliForMode(options.dryRun === true);
  await maybeRun(
    options.dryRun === true,
    ov,
    withIdentity(config, ['import', expandPath(options.path), options.targetUri ?? 'viking://']),
  );
}

async function inferRecallUri(config: RuntimeConfig, query: string): Promise<string | undefined> {
  const normalizedQuery = query.toLowerCase();
  if (/\bskills?\b/.test(normalizedQuery)) {
    const project = await inferProjectFromQuery(config, normalizedQuery);
    return project
      ? `viking://resources/agent-skills/repo-local-${uriSegment(project.name)}`
      : 'viking://resources/agent-skills';
  }

  const project = await inferProjectFromQuery(config, normalizedQuery);
  return project ? trimTrailingSlash(project.uri) : undefined;
}

async function inferProjectFromQuery(
  config: RuntimeConfig,
  normalizedQuery: string,
): Promise<ProjectManifest | undefined> {
  try {
    const manifest = await readSeedManifest(config.manifestPath);
    return manifest.projects.find(project => normalizedQuery.includes(project.name.toLowerCase()));
  } catch (_err: unknown) {
    return undefined;
  }
}

async function commandCheck(name: string, args: readonly string[]): Promise<DoctorCheck> {
  const executable = await findExecutable([name]);
  if (!executable) {
    return {name, status: 'fail', detail: 'missing from PATH'};
  }
  const result = await runCommand(executable, args, {allowFailure: true});
  return {
    name,
    status: result.exitCode === 0 ? 'ok' : 'warn',
    detail: firstLine(result.stdout || result.stderr) || executable,
  };
}

async function commandPresenceCheck(name: string, args: readonly string[]): Promise<DoctorCheck> {
  const executable = await findExecutable([name]);
  if (!executable) {
    return {name, status: 'warn', detail: 'missing; only needed for MCP install'};
  }
  const result = await runCommand(executable, args, {allowFailure: true});
  return {
    name,
    status: 'ok',
    detail: firstLine(result.stdout || result.stderr) || executable,
  };
}

async function firstCommandCheck(
  name: string,
  commands: readonly string[],
  args: readonly string[],
): Promise<DoctorCheck> {
  for (const command of commands) {
    const executable = await findExecutable([command]);
    if (!executable) {
      continue;
    }
    const result = await runCommand(executable, args, {allowFailure: true});
    return {
      name,
      status: result.exitCode === 0 ? 'ok' : 'warn',
      detail: `${command}: ${firstLine(result.stdout || result.stderr) || executable}`,
    };
  }
  return {name, status: 'fail', detail: `none found: ${commands.join(', ')}`};
}

async function localEmbeddingCheck(): Promise<DoctorCheck> {
  const serverPath = await findExecutable([OPENVIKING_SERVER_COMMAND]);
  if (!serverPath) {
    return {name: 'local embedding extra', status: 'warn', detail: 'openviking-server missing'};
  }
  const hasDependency = await hasLocalEmbeddingDependency(serverPath);
  if (hasDependency === undefined) {
    return {
      name: 'local embedding extra',
      status: 'warn',
      detail: 'could not inspect tool Python; install openviking[local-embed] or configure a remote embedding provider',
    };
  }
  return hasDependency
    ? {name: 'local embedding extra', status: 'ok', detail: 'llama_cpp import works'}
    : {
        name: 'local embedding extra',
        status: 'warn',
        detail: 'llama_cpp missing; install will repair with openviking[local-embed]',
      };
}

async function commandShimCheck(): Promise<DoctorCheck> {
  const shimPath = join(expandPath(process.env.THREADNOTE_BIN_DIR ?? '~/.local/bin'), 'threadnote');
  const content = await readFileIfExists(shimPath);
  if (content === undefined) {
    return {name: 'threadnote shim', status: 'warn', detail: `${shimPath} missing; repair will create it`};
  }
  if (!isManagedCommandShim(content)) {
    return {
      name: 'threadnote shim',
      status: 'warn',
      detail: `${shimPath} exists but was not generated by this tool; repair will not overwrite it`,
    };
  }
  if (content !== renderCommandShim()) {
    return {
      name: 'threadnote shim',
      status: 'warn',
      detail: `${shimPath} points at a different checkout; repair will rewrite it`,
    };
  }
  return {name: 'threadnote shim', status: 'ok', detail: shimPath};
}

async function hasLocalEmbeddingDependency(serverPath: string): Promise<boolean | undefined> {
  const pythonPath = await siblingPythonForExecutable(serverPath);
  if (!pythonPath) {
    return undefined;
  }
  const result = await runCommand(pythonPath, ['-c', 'import llama_cpp'], {allowFailure: true});
  return result.exitCode === 0;
}

async function siblingPythonForExecutable(executablePath: string): Promise<string | undefined> {
  let resolvedPath: string;
  try {
    resolvedPath = await realpath(executablePath);
  } catch (_err: unknown) {
    return undefined;
  }
  const pythonPath = join(dirname(resolvedPath), 'python');
  return (await exists(pythonPath)) ? pythonPath : undefined;
}

async function manifestCheck(path: string): Promise<DoctorCheck> {
  try {
    const manifest = await readSeedManifest(path);
    return {name: 'manifest', status: 'ok', detail: `${path} (${manifest.projects.length} project(s))`};
  } catch (err: unknown) {
    return {name: 'manifest', status: 'fail', detail: errorMessage(err)};
  }
}

async function fileCheck(path: string, label: string): Promise<DoctorCheck> {
  return (await exists(path))
    ? {name: label, status: 'ok', detail: path}
    : {name: label, status: 'fail', detail: `${path} missing`};
}

async function healthCheck(config: RuntimeConfig): Promise<DoctorCheck> {
  try {
    const body = await readOpenVikingHealth(config, 1200);
    return {name: 'openviking health', status: 'ok', detail: firstLine(body) || 'healthy'};
  } catch (err: unknown) {
    return {name: 'openviking health', status: 'warn', detail: errorMessage(err)};
  }
}

async function readOpenVikingHealth(config: RuntimeConfig, timeoutMs: number): Promise<string> {
  return httpGetText(`http://${config.host}:${config.port}/health`, timeoutMs);
}

async function readOpenVikingHealthIfAvailable(config: RuntimeConfig, timeoutMs: number): Promise<string | undefined> {
  try {
    return await readOpenVikingHealth(config, timeoutMs);
  } catch (_err: unknown) {
    return undefined;
  }
}

async function getInstallCommand(
  config: RuntimeConfig,
  preferred: PackageManager | undefined,
  force: boolean,
): Promise<MappedCommand> {
  const packageSpec = `${OPENVIKING_PACKAGE_NAME}==${config.openVikingVersion}`;
  const manager = preferred ?? (await detectPackageManager());
  if (manager === 'pipx') {
    return {executable: 'pipx', args: force ? ['install', '--force', packageSpec] : ['install', packageSpec]};
  }
  if (manager === 'uv') {
    return {
      executable: 'uv',
      args: force ? ['tool', 'install', '--force', packageSpec] : ['tool', 'install', packageSpec],
    };
  }
  const pipArgs = ['-m', 'pip', 'install', '--user'];
  if (force) {
    pipArgs.push('--upgrade', '--force-reinstall');
  }
  pipArgs.push(packageSpec);
  return {executable: 'python3', args: pipArgs};
}

async function detectPackageManager(): Promise<PackageManager> {
  if (await findExecutable(['pipx'])) {
    return 'pipx';
  }
  if (await findExecutable(['uv'])) {
    return 'uv';
  }
  return 'pip';
}

async function writeTemplateIfMissing(options: {
  readonly config: RuntimeConfig;
  readonly destinationPath: string;
  readonly dryRun: boolean;
  readonly shouldRepair?: (content: string) => boolean;
  readonly templatePath: string;
}): Promise<void> {
  if (await exists(options.destinationPath)) {
    const currentContent = await readFile(options.destinationPath, 'utf8');
    if (options.shouldRepair?.(currentContent) !== true) {
      console.log(`Already exists: ${options.destinationPath}`);
      return;
    }
    const rendered = renderTemplate(await readFile(options.templatePath, 'utf8'), options.config);
    if (options.dryRun) {
      console.log(`Would repair generated config: ${options.destinationPath}`);
      return;
    }
    const backupPath = `${options.destinationPath}.legacy-${safeTimestamp()}`;
    await writeFile(backupPath, currentContent, {encoding: 'utf8', mode: 0o600});
    await chmod(backupPath, 0o600);
    await writeFile(options.destinationPath, rendered, {encoding: 'utf8', mode: 0o600});
    await chmod(options.destinationPath, 0o600);
    console.log(`Repaired generated config: ${options.destinationPath}`);
    console.log(`Backup: ${backupPath}`);
    return;
  }
  const rendered = renderTemplate(await readFile(options.templatePath, 'utf8'), options.config);
  if (options.dryRun) {
    console.log(`Would write ${options.destinationPath}`);
    return;
  }
  await ensureDirectory(dirname(options.destinationPath), false);
  await writeFile(options.destinationPath, rendered, {encoding: 'utf8', mode: 0o600});
  await chmod(options.destinationPath, 0o600);
  console.log(`Wrote ${options.destinationPath}`);
}

async function installCommandShim(dryRun: boolean): Promise<void> {
  const binDir = expandPath(process.env.THREADNOTE_BIN_DIR ?? '~/.local/bin');
  const shimPath = join(binDir, 'threadnote');
  const existingContent = await readFileIfExists(shimPath);
  if (existingContent && !isManagedCommandShim(existingContent)) {
    console.log(`WARN not overwriting existing command shim: ${shimPath}`);
    return;
  }

  const content = renderCommandShim();
  if (existingContent === content) {
    console.log(`Already exists: ${shimPath}`);
    return;
  }
  if (dryRun) {
    console.log(`Would write command shim: ${shimPath}`);
    return;
  }
  await ensureDirectory(binDir, false);
  await writeFile(shimPath, content, {encoding: 'utf8', mode: 0o755});
  await chmod(shimPath, 0o755);
  console.log(`Wrote command shim: ${shimPath}`);
}

function renderCommandShim(): string {
  const root = toolRoot();
  return [
    '#!/usr/bin/env bash',
    `# ${SHIM_MARKER}`,
    'set -euo pipefail',
    `THREADNOTE_ROOT=${shellQuote(root)}`,
    'THREADNOTE_ENTRY="$THREADNOTE_ROOT/dist/threadnote.cjs"',
    'if [ ! -f "$THREADNOTE_ENTRY" ]; then',
    '  THREADNOTE_ENTRY="$THREADNOTE_ROOT/bin/threadnote.cjs"',
    'fi',
    'THREADNOTE_CALLER_CWD="$PWD"',
    'export THREADNOTE_CALLER_CWD',
    'if command -v node >/dev/null 2>&1; then',
    '  exec node "$THREADNOTE_ENTRY" "$@"',
    'fi',
    'if command -v bun >/dev/null 2>&1; then',
    '  exec bun "$THREADNOTE_ENTRY" "$@"',
    'fi',
    'if command -v deno >/dev/null 2>&1; then',
    '  exec deno run --allow-read --allow-write --allow-run --allow-env --allow-net "$THREADNOTE_ENTRY" "$@"',
    'fi',
    'echo "threadnote requires Node.js, Bun, or Deno." >&2',
    'exit 127',
    '',
  ].join('\n');
}

function isManagedCommandShim(content: string): boolean {
  return content.includes(SHIM_MARKER);
}

async function installLaunchAgent(config: RuntimeConfig, dryRun: boolean): Promise<void> {
  if (platform() !== 'darwin') {
    throw new Error('launchd autostart is only supported on macOS.');
  }
  const source = join(toolRoot(), 'config', 'launchd', `${LAUNCHD_LABEL}.plist.template`);
  const destination = expandPath(`~/Library/LaunchAgents/${LAUNCHD_LABEL}.plist`);
  const rendered = renderTemplate(await readFile(source, 'utf8'), config);
  if (dryRun) {
    console.log(`Would write ${destination}`);
    console.log(`Would run: launchctl unload ${destination}`);
    console.log(`Would run: launchctl load ${destination}`);
    console.log(`Would run: launchctl start ${LAUNCHD_LABEL}`);
    return;
  }
  await ensureDirectory(dirname(destination), false);
  await writeFile(destination, rendered, 'utf8');
  await maybeRun(false, 'launchctl', ['unload', destination], {allowFailure: true});
  await maybeRun(false, 'launchctl', ['load', destination]);
  await maybeRun(false, 'launchctl', ['start', LAUNCHD_LABEL]);
  console.log(`Installed and started ${LAUNCHD_LABEL}`);
}

function openVikingServerArgs(config: RuntimeConfig): readonly string[] {
  return ['--config', join(config.agentContextHome, 'ov.conf'), '--host', config.host, '--port', String(config.port)];
}

async function collectSeedCandidates(
  project: ProjectManifest,
  projectRoot: string,
  ignorePatterns: readonly string[],
): Promise<readonly SeedCandidate[]> {
  const candidates: SeedCandidate[] = [];
  const seen = new Set<string>();
  for (const pattern of project.seed) {
    const files = await resolveProjectPattern(projectRoot, pattern);
    for (const filePath of files) {
      const relativePath = toPosixPath(relative(projectRoot, filePath));
      if (seen.has(relativePath) || matchesIgnore(relativePath, ignorePatterns)) {
        continue;
      }
      seen.add(relativePath);
      candidates.push({
        destinationUri: `${trimTrailingSlash(project.uri)}/${relativePath}`,
        filePath,
        projectName: project.name,
        relativePath,
      });
    }
  }
  return candidates;
}

async function resolveProjectPattern(projectRoot: string, pattern: string): Promise<readonly string[]> {
  const normalizedPattern = toPosixPath(pattern);
  if (!hasGlob(normalizedPattern)) {
    const filePath = join(projectRoot, normalizedPattern);
    return (await isFile(filePath)) ? [filePath] : [];
  }

  const globBase = getGlobBase(normalizedPattern);
  const basePath = join(projectRoot, globBase);
  if (!(await exists(basePath))) {
    return [];
  }

  const regex = globToRegExp(normalizedPattern);
  const files = await walkFiles(basePath);
  return files.filter(filePath => regex.test(toPosixPath(relative(projectRoot, filePath))));
}

async function prepareSeedFile(
  config: RuntimeConfig,
  candidate: SeedCandidate,
  dryRun: boolean,
): Promise<string | undefined> {
  const content = await readFile(candidate.filePath, 'utf8');
  const redactedContent = shouldRedactPath(candidate.relativePath)
    ? redactContent(candidate.relativePath, content)
    : content;
  const secretMatches = detectSecretMatches(redactedContent);
  if (secretMatches.length > 0) {
    console.log(
      `SKIP ${candidate.projectName}/${candidate.relativePath}: possible secret (${secretMatches
        .slice(0, MAX_SECRET_MATCHES_TO_PRINT)
        .join(', ')})`,
    );
    return undefined;
  }

  if (redactedContent === content) {
    return candidate.filePath;
  }

  const redactedPath = join(config.agentContextHome, 'redacted', candidate.projectName, candidate.relativePath);
  if (dryRun) {
    console.log(`Would write redacted copy: ${redactedPath}`);
    return redactedPath;
  }
  await ensureDirectory(dirname(redactedPath), false);
  await writeFile(redactedPath, redactedContent, {encoding: 'utf8', mode: 0o600});
  await chmod(redactedPath, 0o600);
  return redactedPath;
}

async function collectSkillCandidates(config: RuntimeConfig): Promise<readonly SkillCandidate[]> {
  const sources: Array<{readonly pattern: string; readonly source: string}> = [
    {pattern: '~/.codex/skills/**/SKILL.md', source: 'codex-global'},
    {pattern: '~/.codex/plugins/cache/**/skills/**/SKILL.md', source: 'codex-plugin-cache'},
    {pattern: '~/.claude/skills/**/SKILL.md', source: 'claude-global'},
  ];

  try {
    const manifest = await readSeedManifest(config.manifestPath);
    for (const project of manifest.projects) {
      sources.push({
        pattern: `${project.path}/.claude/skills/**/SKILL.md`,
        source: `repo-local:${project.name}`,
      });
    }
  } catch (err: unknown) {
    console.log(`WARN cannot read manifest for repo-local skill discovery: ${errorMessage(err)}`);
  }

  const seenHashes = new Set<string>();
  const skills: SkillCandidate[] = [];
  for (const source of sources) {
    const files = await resolveAbsolutePattern(expandPath(source.pattern));
    for (const filePath of files) {
      const content = await readFile(filePath, 'utf8');
      const matches = detectSecretMatches(content);
      if (matches.length > 0) {
        console.log(`SKIP skill with possible secret: ${filePath}`);
        continue;
      }
      const hash = sha256(content);
      if (seenHashes.has(hash)) {
        continue;
      }
      seenHashes.add(hash);
      skills.push({filePath, hash, source: source.source});
    }
  }
  return skills;
}

async function resolveAbsolutePattern(pattern: string): Promise<readonly string[]> {
  const normalizedPattern = toPosixPath(pattern);
  if (!hasGlob(normalizedPattern)) {
    return (await isFile(normalizedPattern)) ? [normalizedPattern] : [];
  }
  const globBase = getGlobBase(normalizedPattern);
  const basePath = globBase.startsWith('/') ? globBase : `/${globBase}`;
  if (!(await exists(basePath))) {
    return [];
  }
  const regex = globToRegExp(normalizedPattern);
  const files = await walkFiles(basePath);
  return files.filter(filePath => regex.test(toPosixPath(filePath)));
}

function buildMcpInstallCommand(
  config: RuntimeConfig,
  agent: AgentClient,
  name: string,
  options: {
    readonly bearerTokenEnvVar?: string;
    readonly nativeHttp: boolean;
    readonly scope?: ClaudeMcpScope;
    readonly url: string;
  },
): MappedCommand {
  const claudeCwd = getInvocationCwd();
  const claudeScope = options.scope ?? 'user';
  if (!options.nativeHttp) {
    const command = mcpAdapterCommand();
    const env = mcpEnvironment(config);
    if (agent === 'codex') {
      return {
        executable: 'codex',
        args: ['mcp', 'add', ...env.flatMap(value => ['--env', value]), name, '--', ...command],
      };
    }
    return {
      executable: 'claude',
      args: ['mcp', 'add', '--scope', claudeScope, name, '--', '/usr/bin/env', ...env, ...command],
      cwd: claudeCwd,
    };
  }

  if (agent === 'codex') {
    const args = ['mcp', 'add', name, '--url', options.url];
    if (options.bearerTokenEnvVar) {
      args.push('--bearer-token-env-var', options.bearerTokenEnvVar);
    }
    return {executable: 'codex', args};
  }

  const args = ['mcp', 'add', '--scope', claudeScope, '--transport', 'http', name, options.url];
  if (options.bearerTokenEnvVar) {
    const token = process.env[options.bearerTokenEnvVar];
    if (token) {
      args.push('--header', `Authorization: Bearer ${token}`);
    } else {
      console.log(
        `WARN ${options.bearerTokenEnvVar} is not set; installing Claude MCP without an Authorization header.`,
      );
    }
  }
  return {executable: 'claude', args, cwd: claudeCwd};
}

function mcpAdapterCommand(): readonly string[] {
  return [join(toolRoot(), 'bin', 'threadnote-mcp-server.cjs')];
}

function buildMcpRemoveCommand(agent: AgentClient, name: string): MappedCommand {
  return agent === 'codex'
    ? {executable: 'codex', args: ['mcp', 'remove', name]}
    : {executable: 'claude', args: ['mcp', 'remove', name], cwd: getInvocationCwd()};
}

function mcpEnvironment(config: RuntimeConfig): readonly string[] {
  return [
    `THREADNOTE_HOME=${config.agentContextHome}`,
    `THREADNOTE_ACCOUNT=${config.account}`,
    `THREADNOTE_USER=${config.user}`,
    `THREADNOTE_AGENT_ID=${config.agentId}`,
  ];
}

function withIdentity(config: RuntimeConfig, args: readonly string[]): readonly string[] {
  return [...args, '--account', config.account, '--user', config.user, '--agent-id', config.agentId];
}

function skillResourceUri(skill: SkillCandidate): string {
  return `viking://resources/agent-skills/${uriSegment(skill.source)}/${uriSegment(basename(dirname(skill.filePath)))}-${skill.hash.slice(0, 12)}.md`;
}

function uriSegment(value: string): string {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return normalized.length > 0 ? normalized : 'unknown';
}

function printMcpSnippet(
  config: RuntimeConfig,
  agent: AgentClient,
  name: string,
  options: {readonly nativeHttp: boolean; readonly scope?: ClaudeMcpScope; readonly url: string},
): void {
  const snippetPath = join(config.agentContextHome, 'mcp', `${name}.${agent}.${agent === 'codex' ? 'toml' : 'txt'}`);
  const command = buildMcpInstallCommand(config, agent, name, {
    nativeHttp: options.nativeHttp,
    scope: options.scope,
    url: options.url,
  });
  const snippet = `${formatShellCommand(command.executable, command.args)}\n`;
  console.log(`\nSnippet (${snippetPath}):\n${snippet}`);
}

async function storeMemory(config: RuntimeConfig, memory: string, dryRun: boolean): Promise<void> {
  const ov = await openVikingCliForMode(dryRun);
  const memoryPath = join(config.agentContextHome, 'last-memory.txt');
  if (dryRun) {
    console.log(memory);
    console.log('\nWould run:');
    console.log(formatShellCommand(ov, withIdentity(config, ['add-memory', memory])));
    return;
  }
  await writeFile(memoryPath, memory, {encoding: 'utf8', mode: 0o600});
  await chmod(memoryPath, 0o600);
  await maybeRun(false, ov, withIdentity(config, ['add-memory', memory]));
}

async function buildHandoff(options: HandoffOptions): Promise<string> {
  const repoRoot = (await gitValue(['rev-parse', '--show-toplevel'])) ?? getInvocationCwd();
  const branch = (await gitValue(['branch', '--show-current'], repoRoot)) ?? 'unknown';
  const status = (await gitValue(['status', '--short'], repoRoot)) ?? '';
  const diffStat = (await gitValue(['diff', '--stat', 'HEAD'], repoRoot)) ?? '';
  const touchedFiles = await gitTouchedFiles(repoRoot);
  return [
    'HANDOFF',
    `repo: ${basename(repoRoot)}`,
    `repo_path: ${repoRoot}`,
    `branch: ${branch || 'unknown'}`,
    `source_agent_client: ${options.sourceAgentClient ?? 'codex'}`,
    `timestamp: ${new Date().toISOString()}`,
    `task: ${options.task ?? 'unspecified'}`,
    '',
    'files_touched:',
    formatBlock(touchedFiles, '- none'),
    '',
    'git_status:',
    formatBlock(status, '- clean'),
    '',
    'diff_stat:',
    formatBlock(diffStat, '- none'),
    '',
    'tests:',
    options.tests ?? '- not recorded',
    '',
    'blockers:',
    options.blockers ?? '- none recorded',
    '',
    'next_step:',
    options.nextStep ?? '- inspect the current repo state and continue from this handoff',
  ].join('\n');
}

async function gitValue(args: readonly string[], cwd = getInvocationCwd()): Promise<string | undefined> {
  const result = await runCommand('git', args, {allowFailure: true, cwd});
  if (result.exitCode !== 0) {
    return undefined;
  }
  return result.stdout.trim();
}

async function gitTouchedFiles(cwd: string): Promise<string> {
  const changedFiles = await gitValue(['diff', '--name-only', 'HEAD'], cwd);
  const untrackedFiles = await gitValue(['ls-files', '--others', '--exclude-standard'], cwd);
  const files = new Set<string>();
  for (const value of [changedFiles, untrackedFiles]) {
    for (const line of (value ?? '').split('\n')) {
      const trimmed = line.trim();
      if (trimmed) {
        files.add(trimmed);
      }
    }
  }
  return [...files].sort().join('\n');
}

function formatBlock(value: string, emptyValue: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    return emptyValue;
  }
  return trimmed
    .split('\n')
    .map(line => `- ${line}`)
    .join('\n');
}

async function readSeedManifest(path: string): Promise<SeedManifest> {
  const raw = await readFile(path, 'utf8');
  const loaded = yaml.load(raw);
  if (!isJsonObject(loaded)) {
    throw new Error(`Manifest must be an object: ${path}`);
  }
  const version = readNumber(loaded, 'version');
  const projectsValue = loaded.projects;
  if (!Array.isArray(projectsValue)) {
    throw new Error(`Manifest projects must be an array: ${path}`);
  }
  const projects: ProjectManifest[] = [];
  for (const projectValue of projectsValue) {
    if (!isJsonObject(projectValue)) {
      throw new Error(`Manifest project must be an object: ${path}`);
    }
    const seed = readStringArray(projectValue, 'seed');
    projects.push({
      name: readString(projectValue, 'name'),
      path: readString(projectValue, 'path'),
      seed,
      uri: readString(projectValue, 'uri'),
    });
  }

  let futureMonorepo: SeedManifest['futureMonorepo'];
  if (isJsonObject(loaded.future_monorepo)) {
    futureMonorepo = {
      pathCandidates: readStringArray(loaded.future_monorepo, 'path_candidates'),
      uri: readString(loaded.future_monorepo, 'uri'),
    };
  }
  return {futureMonorepo, projects, version};
}

function readString(object: JsonObject, key: string): string {
  const value = object[key];
  if (typeof value !== 'string' || value.length === 0) {
    throw new Error(`Expected non-empty string for ${key}`);
  }
  return value;
}

function readNumber(object: JsonObject, key: string): number {
  const value = object[key];
  if (typeof value !== 'number') {
    throw new Error(`Expected number for ${key}`);
  }
  return value;
}

function readStringArray(object: JsonObject, key: string): readonly string[] {
  const value = object[key];
  if (!Array.isArray(value) || !value.every(item => typeof item === 'string')) {
    throw new Error(`Expected string array for ${key}`);
  }
  return value;
}

function isJsonObject(value: unknown): value is JsonObject {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function shouldRepairOpenVikingConfig(content: string, config: RuntimeConfig): boolean {
  const parsed = parseJsonConfigObject(content);
  if (!parsed) {
    return false;
  }
  if (isLegacyOpenVikingConfig(parsed)) {
    return true;
  }
  return (
    isGeneratedLocalPilotConfig(parsed, config) &&
    (parsed.auto_generate_l0 !== false || parsed.auto_generate_l1 !== false)
  );
}

function isLegacyOpenVikingConfig(parsed: JsonObject): boolean {
  return (
    isJsonObject(parsed.server) &&
    typeof parsed.server.storage_dir === 'string' &&
    isJsonObject(parsed.identity) &&
    isJsonObject(parsed.privacy) &&
    isJsonObject(parsed.models)
  );
}

function isGeneratedLocalPilotConfig(parsed: JsonObject, config: RuntimeConfig): boolean {
  const allowedKeys = new Set([
    'auto_generate_l0',
    'auto_generate_l1',
    'default_account',
    'default_agent',
    'default_user',
    'server',
    'storage',
  ]);
  if (Object.keys(parsed).some(key => !allowedKeys.has(key))) {
    return false;
  }
  if (parsed.default_account !== config.account || parsed.default_agent !== config.agentId) {
    return false;
  }
  if (typeof parsed.default_user !== 'string') {
    return false;
  }
  if (!isJsonObject(parsed.storage) || parsed.storage.workspace !== join(config.agentContextHome, 'data')) {
    return false;
  }
  return (
    isJsonObject(parsed.server) &&
    parsed.server.host === config.host &&
    String(parsed.server.port) === String(config.port)
  );
}

function shouldRepairLegacyOvCliConfig(content: string): boolean {
  const parsed = parseJsonConfigObject(content);
  if (!parsed) {
    return false;
  }
  return typeof parsed.server_url === 'string' && isJsonObject(parsed.identity);
}

function parseJsonConfigObject(content: string): JsonObject | undefined {
  try {
    const parsed: unknown = JSON.parse(content);
    return isJsonObject(parsed) ? parsed : undefined;
  } catch (_err: unknown) {
    return undefined;
  }
}

async function loadIgnorePatterns(): Promise<readonly string[]> {
  const raw = await readFile(join(toolRoot(), '.threadnoteignore'), 'utf8');
  return raw
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0 && !line.startsWith('#'));
}

function matchesIgnore(relativePath: string, patterns: readonly string[]): boolean {
  const path = toPosixPath(relativePath);
  for (const pattern of patterns) {
    const normalizedPattern = toPosixPath(pattern);
    if (normalizedPattern.endsWith('/')) {
      const directory = normalizedPattern.slice(0, -1);
      if (path === directory || path.includes(`/${directory}/`) || path.startsWith(`${directory}/`)) {
        return true;
      }
      continue;
    }
    if (globToRegExp(normalizedPattern).test(path) || globToRegExp(`**/${normalizedPattern}`).test(path)) {
      return true;
    }
  }
  return false;
}

function shouldRedactPath(relativePath: string): boolean {
  const path = toPosixPath(relativePath);
  return (
    path.endsWith('.mcp.json') ||
    path.endsWith('config.toml') ||
    path.includes('/settings') ||
    path.includes('/settings.local')
  );
}

function redactContent(relativePath: string, content: string): string {
  if (relativePath.endsWith('.json')) {
    try {
      const parsed: unknown = JSON.parse(content);
      return `${JSON.stringify(redactJsonValue(parsed), null, 2)}\n`;
    } catch (_err: unknown) {
      return redactText(content);
    }
  }
  return redactText(content);
}

function redactJsonValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(item => redactJsonValue(item));
  }
  if (!isJsonObject(value)) {
    return value;
  }
  const output: Record<string, unknown> = {};
  for (const [key, nestedValue] of Object.entries(value)) {
    output[key] = isSensitiveKey(key) ? '[REDACTED]' : redactJsonValue(nestedValue);
  }
  return output;
}

function redactText(content: string): string {
  return content
    .replace(
      /([A-Za-z0-9_.-]*(?:token|secret|password|api[_-]?key|authorization)[A-Za-z0-9_.-]*\s*[:=]\s*)("[^"]+"|'[^']+'|Bearer\s+[^'"\s]+|\S+)/gi,
      '$1[REDACTED]',
    )
    .replace(/Bearer\s+[A-Za-z0-9._~+/=-]+/gi, 'Bearer [REDACTED]')
    .replace(/sk-[A-Za-z0-9_-]{16,}/g, 'sk-[REDACTED]')
    .replace(/gh[pousr]_[A-Za-z0-9_]{16,}/g, 'gh_[REDACTED]');
}

function isSensitiveKey(key: string): boolean {
  return /token|secret|password|credential|authorization|api[_-]?key|client[_-]?secret|bearer/i.test(key);
}

function detectSecretMatches(content: string): readonly string[] {
  const detectors: Array<{readonly label: string; readonly regex: RegExp}> = [
    {label: 'private-key', regex: /-----BEGIN [A-Z ]*PRIVATE KEY-----/},
    {label: 'openai-key', regex: /sk-[A-Za-z0-9_-]{24,}/},
    {label: 'github-token', regex: /gh[pousr]_[A-Za-z0-9_]{24,}/},
    {label: 'slack-token', regex: /xox[abprs]-[A-Za-z0-9-]{24,}/},
    {label: 'bearer-token', regex: /Bearer\s+[A-Za-z0-9._~+/=-]{24,}/i},
    {label: 'aws-access-key', regex: /AKIA[0-9A-Z]{16}/},
  ];
  const matches: string[] = [];
  for (const detector of detectors) {
    if (detector.regex.test(content)) {
      matches.push(detector.label);
    }
  }
  return matches;
}

async function walkFiles(root: string): Promise<readonly string[]> {
  const files: string[] = [];
  async function visit(path: string): Promise<void> {
    let pathStat;
    try {
      pathStat = await lstat(path);
    } catch (_err: unknown) {
      return;
    }
    if (pathStat.isSymbolicLink()) {
      return;
    }
    if (pathStat.isFile()) {
      files.push(path);
      return;
    }
    if (!pathStat.isDirectory()) {
      return;
    }
    const entries = await readdir(path);
    for (const entry of entries) {
      await visit(join(path, entry));
    }
  }
  await visit(root);
  return files;
}

function globToRegExp(glob: string): RegExp {
  let output = '^';
  for (let index = 0; index < glob.length; index += 1) {
    const char = glob[index];
    if (char === '*') {
      const next = glob[index + 1];
      if (next === '*') {
        const afterNext = glob[index + 2];
        if (afterNext === '/') {
          output += '(?:.*/)?';
          index += 2;
        } else {
          output += '.*';
          index += 1;
        }
      } else {
        output += '[^/]*';
      }
    } else if (char === '?') {
      output += '[^/]';
    } else {
      output += escapeRegExp(char);
    }
  }
  output += '$';
  return new RegExp(output);
}

function getGlobBase(pattern: string): string {
  const parts = pattern.split('/');
  const baseParts: string[] = [];
  for (const part of parts) {
    if (hasGlob(part)) {
      break;
    }
    baseParts.push(part);
  }
  return baseParts.length === 0 ? '.' : baseParts.join('/');
}

function hasGlob(path: string): boolean {
  return path.includes('*') || path.includes('?');
}

function escapeRegExp(value: string): string {
  return value.replace(/[\\^$+?.()|[\]{}]/g, '\\$&');
}

async function requiredOpenVikingCli(): Promise<string> {
  const command = await findExecutable(['ov', 'openviking']);
  if (!command) {
    throw new Error('Neither ov nor openviking was found in PATH. Run threadnote install first.');
  }
  return command;
}

async function openVikingCliForMode(dryRun: boolean): Promise<string> {
  if (dryRun) {
    return (await findExecutable(['ov', 'openviking'])) ?? 'ov';
  }
  return requiredOpenVikingCli();
}

async function requiredExecutable(command: string): Promise<string> {
  const executable = await findExecutable([command]);
  if (!executable) {
    throw new Error(`${command} was not found in PATH.`);
  }
  return executable;
}

async function findExecutable(commands: readonly string[]): Promise<string | undefined> {
  for (const command of commands) {
    const result = await runCommand('which', [command], {allowFailure: true});
    if (result.exitCode === 0 && result.stdout.trim()) {
      return result.stdout.trim();
    }
  }
  return undefined;
}

async function maybeRun(
  dryRun: boolean,
  executable: string,
  args: readonly string[],
  options: {readonly allowFailure?: boolean; readonly cwd?: string} = {},
): Promise<CommandResult | undefined> {
  const cwdSuffix = options.cwd ? ` (cwd: ${options.cwd})` : '';
  console.log(`${dryRun ? 'Would run' : 'Running'}: ${formatShellCommand(executable, args)}${cwdSuffix}`);
  if (dryRun) {
    return undefined;
  }
  const result = await runCommand(executable, args, {allowFailure: options.allowFailure === true, cwd: options.cwd});
  if (result.stdout.trim()) {
    console.log(result.stdout.trim());
  }
  if (result.stderr.trim()) {
    console.error(result.stderr.trim());
  }
  return result;
}

async function runCommand(
  executable: string,
  args: readonly string[],
  options: {readonly allowFailure?: boolean; readonly cwd?: string} = {},
): Promise<CommandResult> {
  return new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(executable, args, {cwd: options.cwd});
    const stdoutChunks: string[] = [];
    const stderrChunks: string[] = [];
    child.stdout.on('data', chunk => {
      stdoutChunks.push(String(chunk));
    });
    child.stderr.on('data', chunk => {
      stderrChunks.push(String(chunk));
    });
    child.on('error', err => {
      if (options.allowFailure === true) {
        resolvePromise({exitCode: 127, stderr: errorMessage(err), stdout: ''});
      } else {
        rejectPromise(err);
      }
    });
    child.on('close', code => {
      const result = {
        exitCode: code ?? 1,
        stderr: stderrChunks.join(''),
        stdout: stdoutChunks.join(''),
      };
      if (result.exitCode !== 0 && options.allowFailure !== true) {
        rejectPromise(new Error(`${formatShellCommand(executable, args)} failed: ${result.stderr || result.stdout}`));
        return;
      }
      resolvePromise(result);
    });
  });
}

async function runInteractive(executable: string, args: readonly string[]): Promise<number> {
  return new Promise(resolvePromise => {
    const child = spawn(executable, args, {stdio: 'inherit'});
    child.on('close', code => {
      resolvePromise(code ?? 1);
    });
  });
}

async function httpGetText(url: string, timeoutMs: number): Promise<string> {
  return new Promise((resolvePromise, rejectPromise) => {
    const request = httpGet(url, response => {
      const chunks: string[] = [];
      response.on('data', chunk => {
        chunks.push(String(chunk));
      });
      response.on('end', () => {
        const statusCode = response.statusCode ?? 0;
        if (statusCode < 200 || statusCode >= 300) {
          rejectPromise(new Error(`HTTP ${statusCode}`));
          return;
        }
        resolvePromise(chunks.join(''));
      });
    });
    request.setTimeout(timeoutMs, () => {
      request.destroy(new Error(`Timed out after ${timeoutMs}ms`));
    });
    request.on('error', rejectPromise);
  });
}

async function readHttpStatus(url: string, timeoutMs: number): Promise<number | undefined> {
  return new Promise(resolvePromise => {
    const request = httpGet(url, response => {
      response.resume();
      resolvePromise(response.statusCode);
    });
    request.setTimeout(timeoutMs, () => {
      request.destroy();
      resolvePromise(undefined);
    });
    request.on('error', () => {
      resolvePromise(undefined);
    });
  });
}

async function isTcpPortOpen(host: string, port: number, timeoutMs: number): Promise<boolean> {
  return new Promise(resolvePromise => {
    const socket = createConnection({host, port});
    let resolved = false;
    const finish = (value: boolean): void => {
      if (resolved) {
        return;
      }
      resolved = true;
      socket.destroy();
      resolvePromise(value);
    };
    socket.setTimeout(timeoutMs);
    socket.once('connect', () => {
      finish(true);
    });
    socket.once('timeout', () => {
      finish(false);
    });
    socket.once('error', () => {
      finish(false);
    });
  });
}

async function getInputText(optionText: string | undefined, useStdin: boolean): Promise<string> {
  if (optionText !== undefined) {
    return optionText;
  }
  if (!useStdin) {
    return '';
  }
  return new Promise(resolvePromise => {
    const chunks: string[] = [];
    process.stdin.on('data', chunk => {
      chunks.push(String(chunk));
    });
    process.stdin.on('end', () => {
      resolvePromise(chunks.join(''));
    });
  });
}

async function ensureDirectory(path: string, dryRun: boolean): Promise<void> {
  if (dryRun) {
    console.log(`Would create directory: ${path}`);
    return;
  }
  await mkdir(path, {recursive: true});
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch (_err: unknown) {
    return false;
  }
}

async function isFile(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile();
  } catch (_err: unknown) {
    return false;
  }
}

async function isDirectory(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isDirectory();
  } catch (_err: unknown) {
    return false;
  }
}

async function readFileIfExists(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8');
  } catch (_err: unknown) {
    return undefined;
  }
}

function renderTemplate(template: string, config: RuntimeConfig): string {
  return template
    .replaceAll('{{THREADNOTE_HOME}}', config.agentContextHome)
    .replaceAll('{{OPENVIKING_ACCOUNT}}', config.account)
    .replaceAll('{{OPENVIKING_AGENT_ID}}', config.agentId)
    .replaceAll('{{OPENVIKING_HOST}}', config.host)
    .replaceAll('{{OPENVIKING_PORT}}', String(config.port))
    .replaceAll('{{OPENVIKING_USER}}', config.user);
}

function parsePort(value: string): number {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0 || parsed > 65535) {
    throw new Error(`Invalid port: ${value}`);
  }
  return parsed;
}

function parsePositiveInteger(value: string, label: string): number {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    throw new Error(`Invalid ${label}: ${value}`);
  }
  return parsed;
}

function parsePackageManager(value: string): PackageManager {
  if (value === 'pipx' || value === 'uv' || value === 'pip') {
    return value;
  }
  throw new Error(`Invalid package manager: ${value}`);
}

function parseAgentClient(value: string): AgentClient {
  if (value === 'codex' || value === 'claude') {
    return value;
  }
  throw new Error(`Unsupported agent: ${value}. Expected codex or claude.`);
}

function parseClaudeMcpScope(value: string): ClaudeMcpScope {
  if (value === 'local' || value === 'project' || value === 'user') {
    return value;
  }
  throw new Error(`Invalid Claude MCP scope: ${value}. Expected local, project, or user.`);
}

async function resolveRepairMcpClients(value: string): Promise<readonly AgentClient[]> {
  const normalized = value.trim().toLowerCase();
  if (normalized === 'none' || normalized === 'false' || normalized === 'off') {
    return [];
  }

  let requested: readonly AgentClient[];
  if (normalized === 'available' || normalized === 'all') {
    requested = ['codex', 'claude'];
  } else {
    requested = normalized
      .split(',')
      .map(part => part.trim())
      .filter(Boolean)
      .map(parseAgentClient);
  }

  const clients: AgentClient[] = [];
  for (const client of requested) {
    if (!(await findExecutable([client]))) {
      console.log(`WARN ${client} command not found; cannot repair ${client} MCP config.`);
      continue;
    }
    if (!clients.includes(client)) {
      clients.push(client);
    }
  }
  return clients;
}

function assertVikingUri(uri: string): void {
  if (!uri.startsWith('viking://')) {
    throw new Error(`Refusing non-viking URI: ${uri}`);
  }
}

function collectOption(value: string, previous: readonly string[]): readonly string[] {
  return [...previous, value];
}

function expandPath(path: string): string {
  if (path === '~') {
    return homedir();
  }
  if (path.startsWith(`~${sep}`) || path.startsWith('~/')) {
    return join(homedir(), path.slice(2));
  }
  return isAbsolute(path) ? path : resolve(getInvocationCwd(), path);
}

function portablePath(path: string): string {
  const home = homedir();
  const resolvedPath = resolve(path);
  if (resolvedPath === home) {
    return '~';
  }
  if (resolvedPath.startsWith(`${home}${sep}`)) {
    return `~/${resolvedPath
      .slice(home.length + 1)
      .split(sep)
      .join('/')}`;
  }
  return resolvedPath;
}

function getInvocationCwd(): string {
  return process.env.THREADNOTE_CALLER_CWD ?? process.cwd();
}

function toPosixPath(path: string): string {
  return path.split(sep).join('/');
}

function trimTrailingSlash(value: string): string {
  return value.endsWith('/') ? value.slice(0, -1) : value;
}

function parentVikingUri(uri: string): string {
  const trimmedUri = trimTrailingSlash(uri);
  const slashIndex = trimmedUri.lastIndexOf('/');
  return slashIndex <= 'viking://'.length ? trimmedUri : trimmedUri.slice(0, slashIndex);
}

function sha256(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

function safeTimestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

function firstLine(value: string): string {
  return value.split('\n')[0]?.trim() ?? '';
}

function formatStatus(status: CommandStatus): string {
  if (status === 'ok') {
    return 'OK  ';
  }
  if (status === 'warn') {
    return 'WARN';
  }
  return 'FAIL';
}

function formatShellCommand(executable: string, args: readonly string[]): string {
  return redactText([executable, ...args].map(shellQuote).join(' '));
}

function shellQuote(value: string): string {
  if (/^[A-Za-z0-9_./:@=-]+$/.test(value)) {
    return value;
  }
  return `'${value.replaceAll("'", "'\"'\"'")}'`;
}

function toolRoot(): string {
  if (existsSync(join(__dirname, 'package.json'))) {
    return __dirname;
  }
  return resolve(__dirname, '..');
}

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

main().catch(err => {
  console.error(errorMessage(err));
  process.exit(1);
});
