import {Console, Effect, FileSystem, Path, Schema} from 'effect';
import {resolveAgentHostPaths} from './agent_integration/host_paths.js';
import {readFileIfExists} from './utils.js';
import type {HooksInstallOptions} from './types.js';

/**
 * omp loads hook factories from `<agentDir>/hooks/pre/*.{ts,js}`. The managed
 * module is a whole generated file, so the first line doubles as the ownership
 * marker: only content starting with it is replaced or removed.
 */
const OMP_HOOK_FILE_MARKER = '// Generated by threadnote.';

/**
 * The generated factory keeps Threadnote's best-effort hook contract: the
 * commands it runs already swallow their own failures, and this wrapper adds
 * one more guard so a missing `threadnote` on PATH can never block the host.
 */
const OMP_HOOK_MODULE = `${OMP_HOOK_FILE_MARKER} Managed by \`threadnote install-hooks omp --apply\`; remove with \`threadnote install-hooks omp --remove\`.
// Binds omp session lifecycle events to the threadnote hook commands; edits are overwritten on refresh.
export default function threadnoteHooks(pi: {
  exec(command: string, args: string[], options?: {timeout?: number}): Promise<{stdout: string}>;
  on(event: 'session_start' | 'session_before_compact', handler: () => Promise<void>): void;
  sendMessage(message: {customType: string; content: string; display: boolean}): void;
}): void {
  const runHook = async (args: string[]): Promise<string> => {
    try {
      const result = await pi.exec('threadnote', args, {timeout: 30000});
      return typeof result?.stdout === 'string' ? result.stdout.trim() : '';
    } catch {
      return '';
    }
  };

  // Queue the unread Threadnote context for this workspace before the first turn.
  pi.on('session_start', async () => {
    const context = await runHook(['session-start-hook']);
    if (context.length > 0) {
      pi.sendMessage({customType: 'threadnote-session-start', content: context, display: false});
    }
  });

  // Deterministic handoff snapshot before context compaction.
  pi.on('session_before_compact', async () => {
    await runHook(['pre-compact-hook', '--source-agent-client', 'omp']);
  });
}
`;

class OmpHooksConfigError extends Schema.TaggedError<OmpHooksConfigError>()('OmpHooksConfigError', {
  message: Schema.String,
}) {}

export const runOmpHooksInstall = Effect.fn('hooks.installOmp')(function* (options: HooksInstallOptions) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const hookPath = (yield* resolveAgentHostPaths('omp', options.hostRoot))!.hookPath;
  const remove = options.remove === true;
  const apply = options.apply === true && options.dryRun !== true;
  const current = yield* readFileIfExists(hookPath);

  if (remove) {
    if (current === undefined) {
      yield* Console.log(`No managed omp hook found: ${hookPath}`);
      return;
    }
    if (!current.startsWith(OMP_HOOK_FILE_MARKER)) {
      yield* Console.log(`WARN ${hookPath} is not managed by Threadnote; not removing it`);
      return;
    }
    if (!apply) {
      yield* Console.log(`Would remove threadnote-managed omp hook: ${hookPath}`);
      return;
    }
    yield* fs.remove(hookPath);
    yield* Console.log(`Removed threadnote-managed omp hook: ${hookPath}`);
    return;
  }

  if (current !== undefined && !current.startsWith(OMP_HOOK_FILE_MARKER)) {
    return yield* OmpHooksConfigError.make({
      message: `${hookPath} exists and is not managed by Threadnote; not modifying it.`,
    });
  }
  if (current === OMP_HOOK_MODULE) {
    yield* Console.log(`omp session hooks already current: ${hookPath}`);
    return;
  }
  if (!apply) {
    yield* Console.log(
      `${current === undefined ? 'Would write' : 'Would update'} threadnote omp session hooks: ${hookPath}`,
    );
    yield* Console.log('  + session_start: threadnote session-start-hook');
    yield* Console.log('  + session_before_compact: threadnote pre-compact-hook');
    return;
  }
  yield* fs.makeDirectory(path.dirname(hookPath), {recursive: true, mode: 0o700});
  yield* fs.writeFileString(hookPath, OMP_HOOK_MODULE, {mode: 0o644});
  yield* Console.log(`${current === undefined ? 'Wrote' : 'Updated'} threadnote omp session hooks: ${hookPath}`);
});

export const relocateManagedOmpHook = Effect.fn('hooks.relocateManagedOmp')(function* (
  previousHostRoot: string,
  nextHostRoot: string,
  dryRun: boolean,
) {
  if (previousHostRoot === nextHostRoot) return;
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const previousPath = (yield* resolveAgentHostPaths('omp', previousHostRoot))!.hookPath;
  const nextPath = (yield* resolveAgentHostPaths('omp', nextHostRoot))!.hookPath;
  const previous = yield* readFileIfExists(previousPath);
  if (previous === undefined || !previous.startsWith(OMP_HOOK_FILE_MARKER)) return;
  const next = yield* readFileIfExists(nextPath);
  if (next !== undefined && !next.startsWith(OMP_HOOK_FILE_MARKER)) {
    return yield* OmpHooksConfigError.make({
      message: `${nextPath} exists and is not managed by Threadnote; not modifying it.`,
    });
  }
  if (dryRun) {
    yield* Console.log(`Would move threadnote-managed omp hook: ${previousPath} -> ${nextPath}`);
    return;
  }
  yield* fs.makeDirectory(path.dirname(nextPath), {recursive: true, mode: 0o700});
  if (next !== OMP_HOOK_MODULE) yield* fs.writeFileString(nextPath, OMP_HOOK_MODULE, {mode: 0o644});
  yield* fs.remove(previousPath);
  yield* Console.log(`Moved threadnote-managed omp hook: ${previousPath} -> ${nextPath}`);
});

export const hasManagedOmpHooks = Effect.fn('hooks.hasManagedOmpHooks')(function* (hostRoot?: string) {
  const current = yield* readFileIfExists((yield* resolveAgentHostPaths('omp', hostRoot))!.hookPath);
  return current !== undefined && current.startsWith(OMP_HOOK_FILE_MARKER);
});

export const hasCurrentOmpHooks = Effect.fn('hooks.hasCurrentOmpHooks')(function* (hostRoot?: string) {
  const current = yield* readFileIfExists((yield* resolveAgentHostPaths('omp', hostRoot))!.hookPath);
  return current === OMP_HOOK_MODULE;
});
