// Generated by scripts/generate-code-graph-language-catalog.ts. Do not edit by hand.
import {codeGraphLanguagePack as apex} from './apex/pack.js';
import {codeGraphLanguagePack as bash} from './bash/pack.js';
import {codeGraphLanguagePack as c} from './c/pack.js';
import {codeGraphLanguagePack as corpus} from './corpus/pack.js';
import {codeGraphLanguagePack as cpp} from './cpp/pack.js';
import {codeGraphLanguagePack as csharp} from './csharp/pack.js';
import {codeGraphLanguagePack as dart} from './dart/pack.js';
import {codeGraphLanguagePack as documentation} from './documentation/pack.js';
import {codeGraphLanguagePack as elixir} from './elixir/pack.js';
import {codeGraphLanguagePack as fortran} from './fortran/pack.js';
import {codeGraphLanguagePack as go} from './go/pack.js';
import {codeGraphLanguagePack as hcl} from './hcl/pack.js';
import {codeGraphLanguagePack as java} from './java/pack.js';
import {codeGraphLanguagePack as julia} from './julia/pack.js';
import {codeGraphLanguagePack as kotlin} from './kotlin/pack.js';
import {codeGraphLanguagePack as lua} from './lua/pack.js';
import {codeGraphLanguagePack as manifests} from './manifests/pack.js';
import {codeGraphLanguagePack as objectiveC} from './objective-c/pack.js';
import {codeGraphLanguagePack as php} from './php/pack.js';
import {codeGraphLanguagePack as powershell} from './powershell/pack.js';
import {codeGraphLanguagePack as python} from './python/pack.js';
import {codeGraphLanguagePack as razor} from './razor/pack.js';
import {codeGraphLanguagePack as ruby} from './ruby/pack.js';
import {codeGraphLanguagePack as rust} from './rust/pack.js';
import {codeGraphLanguagePack as scala} from './scala/pack.js';
import {codeGraphLanguagePack as schemas} from './schemas/pack.js';
import {codeGraphLanguagePack as solidity} from './solidity/pack.js';
import {codeGraphLanguagePack as svelte} from './svelte/pack.js';
import {codeGraphLanguagePack as swift} from './swift/pack.js';
import {codeGraphLanguagePack as systemverilog} from './systemverilog/pack.js';
import {codeGraphLanguagePack as typescript} from './typescript/pack.js';
import {codeGraphLanguagePack as vue} from './vue/pack.js';
import {codeGraphLanguagePack as zig} from './zig/pack.js';

export const BUILTIN_CODE_GRAPH_LANGUAGE_PACKS = [
  apex,
  bash,
  c,
  corpus,
  cpp,
  csharp,
  dart,
  documentation,
  elixir,
  fortran,
  go,
  hcl,
  java,
  julia,
  kotlin,
  lua,
  manifests,
  objectiveC,
  php,
  powershell,
  python,
  razor,
  ruby,
  rust,
  scala,
  schemas,
  solidity,
  svelte,
  swift,
  systemverilog,
  typescript,
  vue,
  zig,
] as const;
