// Generated by scripts/generate-code-graph-language-catalog.ts. Do not edit by hand.
import {codeGraphLanguagePack as documentation} from './documentation/pack.js';
import {codeGraphLanguagePack as java} from './java/pack.js';
import {codeGraphLanguagePack as kotlin} from './kotlin/pack.js';
import {codeGraphLanguagePack as manifests} from './manifests/pack.js';
import {codeGraphLanguagePack as swift} from './swift/pack.js';
import {codeGraphLanguagePack as typescript} from './typescript/pack.js';

export const BUILTIN_CODE_GRAPH_LANGUAGE_PACKS = [documentation, java, kotlin, manifests, swift, typescript] as const;
