export {
  budgetCachedCodeGraphFacts,
  cachedCodeGraphFactBytes,
  cachedCodeGraphFactByteUpperBound,
  CODE_GRAPH_CACHED_FACT_BYTES_MAXIMUM,
  CODE_GRAPH_REFERENCE_CANDIDATES_PER_REFERENCE_MAXIMUM,
  CODE_GRAPH_REFERENCE_CANDIDATE_BUDGET_DIAGNOSTIC,
  compactCachedFileRelationships,
  finalCodeGraphFactBatches,
} from './fact_budget.js';

export {CodeGraphIndexer} from './indexer_service.js';
export {
  codeGraphIndexEnsuresVectors,
  type CodeGraphCommitLease,
  type CodeGraphIndexerShape,
  type CodeGraphIndexOptions,
  type DirectPersistentCapacityProtection,
} from './indexer_types.js';
export {
  createCachedCodeGraphFactsAttributor,
  deriveCachedCodeGraphFacts,
  hasSameCodeGraphResolutionSurface,
  resolvePersistedReexportTerminals,
  reusableBaseFileSetFingerprint,
} from './indexer_incremental.js';
export {
  addMaterializationReplayMetrics,
  addMaterializationRows,
  cacheContentBatch,
  codeGraphActiveParserCacheKey,
  codeGraphDirectPersistentCapacityProtector,
  codeGraphParserCacheLookupGenerations,
  deduplicateMaterializationRelationships,
  directFullSnapshotIdentity,
  emptyMaterializationReplayMetrics,
  estimatedMaterializationStorageBytes,
  extractorSetIdentity,
  extractorSetIdentityFromPackProvenance,
  factMaterializationBatches,
  graphContentIdentity,
  materializationRowsWithStoreProgress,
  materializationStoragePlan,
  materializationStorageShortfalls,
  parserCacheIdentity,
  persistentMaterializationTransactionBatches,
  shouldReuseReadySnapshotForCleanCommit,
  snapshotIdentity,
  sparseOverlayGraphContentIdentity,
  sparseOverlaySnapshotIdentity,
  type CodeGraphCacheContentCoalescer,
  type CodeGraphCacheExtractedRow,
  type DirectPersistentCapacityContext,
  type CodeGraphMaterializationReplayMetrics,
  type CodeGraphMaterializationReplayObservation,
  type MaterializationStorageAvailability,
  type MaterializationStoragePlan,
  type PersistentMaterializationTransactionCandidate,
} from './indexer_materialization.js';
