import * as BunRuntime from '@effect/platform-bun/BunRuntime';
import * as BunServices from '@effect/platform-bun/BunServices';
import {Console, Effect, FileSystem, Path} from 'effect';

const ROOT_URL = new URL('..', import.meta.url);

const generateCatalog = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const root = yield* path.fromFileUrl(ROOT_URL);
  const languagesRoot = path.join(root, 'src', 'code_graph', 'languages');
  const directories = (yield* fs.readDirectory(languagesRoot)).sort();
  const packs: Array<{readonly alias: string; readonly directory: string}> = [];
  for (const directory of directories) {
    const candidate = path.join(languagesRoot, directory);
    const info = yield* fs.stat(candidate).pipe(Effect.option);
    if (info._tag === 'None' || info.value.type !== 'Directory') continue;
    if (!(yield* fs.exists(path.join(candidate, 'pack.ts')))) continue;
    packs.push({alias: safeIdentifier(directory), directory});
  }
  if (packs.length === 0) return yield* Effect.fail(new Error('No code graph language packs were discovered.'));
  const output = [
    '// Generated by scripts/generate-code-graph-language-catalog.ts. Do not edit by hand.',
    ...packs.map(pack => `import {codeGraphLanguagePack as ${pack.alias}} from './${pack.directory}/pack.js';`),
    '',
    `export const BUILTIN_CODE_GRAPH_LANGUAGE_PACKS = [${packs.map(pack => pack.alias).join(', ')}] as const;`,
    '',
  ].join('\n');
  const target = path.join(languagesRoot, 'catalog.generated.ts');
  const existing = yield* fs.readFileString(target).pipe(Effect.catch(() => Effect.succeed('')));
  if (existing !== output) yield* fs.writeFileString(target, output);
  yield* Console.log(`Generated code graph catalog with ${packs.length} language pack(s).`);
});

function safeIdentifier(value: string): string {
  const identifier = value.replace(/[^A-Za-z0-9_$]+(.)/g, (_, character: string) => character.toUpperCase());
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `pack${identifier}`;
}

BunRuntime.runMain(generateCatalog.pipe(Effect.provide(BunServices.layer)));
