export const DEFAULT_ACCOUNT = 'local';
export const DEFAULT_AGENT_ID = 'threadnote';
export const THREADNOTE_MCP_NAME = 'threadnote';
export const MCP_PROCESS_LIFECYCLE_PROBE_ENV = 'THREADNOTE_MCP_PROCESS_LIFECYCLE_PROBE';
export const MAX_SECRET_MATCHES_TO_PRINT = 5;
export const SHIM_MARKER = 'Generated by threadnote';
export const USER_INSTRUCTIONS_START_MARKER = '<!-- BEGIN THREADNOTE USER INSTRUCTIONS -->';
export const USER_INSTRUCTIONS_END_MARKER = '<!-- END THREADNOTE USER INSTRUCTIONS -->';
export const USER_MANIFEST_NAME = 'seed-manifest.yaml';
export const SEED_STATE_FILE = 'seed-state.json';
export const USER_AGENT_INSTRUCTION_TARGETS = [
  {kind: 'block', label: 'codex user instructions', path: '~/.codex/AGENTS.md'},
  {kind: 'block', label: 'claude user instructions', path: '~/.claude/CLAUDE.md'},
  {kind: 'block', label: 'cursor user rule', path: '~/.cursor/rules/threadnote.md'},
  {
    kind: 'file',
    label: 'copilot user instructions',
    path: '~/.copilot/instructions/threadnote.instructions.md',
  },
] as const;

export const CLAUDE_SETTINGS_PATH = '~/.claude/settings.json';
export const THREADNOTE_HOOK_MARKER = '_threadnote';
export const THREADNOTE_HOOK_MARKER_VALUE = 'managed';
export const HOOK_PRE_COMPACT_COMMAND = 'threadnote pre-compact-hook';
export const HOOK_SESSION_START_COMMAND = 'threadnote session-start-hook';
export const HOOK_AUTO_PRECOMPACT_TOPIC = 'auto-precompact';
export const DEFAULT_SEED_PATTERNS = [
  'AGENTS.md',
  'CLAUDE.md',
  'README.md',
  'CONTRIBUTING.md',
  '.github/AGENTS.md',
  '.github/CLAUDE.md',
  '.github/pull_request_template.md',
  '.github/PULL_REQUEST_TEMPLATE.md',
  '.github/PULL_REQUEST_TEMPLATE/*.md',
  '.claude/commands/*.md',
  '.claude/skills/**/SKILL.md',
  '.claude/**/*.md',
  '.agents/**/*.md',
  'docs/**/*.md',
] as const;
