export const DEFAULT_HOST = '127.0.0.1';
export const DEFAULT_PORT = 1933;
export const DEFAULT_OPENVIKING_VERSION = '0.3.12';
export const DEFAULT_ACCOUNT = 'local';
export const DEFAULT_AGENT_ID = 'threadnote';
export const OPENVIKING_PACKAGE_NAME = 'openviking[local-embed]';
export const OPENVIKING_SERVER_COMMAND = 'openviking-server';
export const OPENVIKING_MCP_NAME = 'threadnote';
export const PYTHON_SYSTEM_CERTS_MODULE = 'pip_system_certs';
export const PYTHON_SYSTEM_CERTS_PACKAGE = 'pip-system-certs';
export const LAUNCHD_LABEL = 'io.threadnote.openviking';
export const MAX_SECRET_MATCHES_TO_PRINT = 5;
export const START_HEALTH_POLL_INTERVAL_MS = 500;
export const START_HEALTH_TIMEOUT_MS = 15_000;
export const SHIM_MARKER = 'Generated by threadnote';
export const USER_INSTRUCTIONS_START_MARKER = '<!-- BEGIN THREADNOTE USER INSTRUCTIONS -->';
export const USER_INSTRUCTIONS_END_MARKER = '<!-- END THREADNOTE USER INSTRUCTIONS -->';
export const USER_MANIFEST_NAME = 'seed-manifest.yaml';
export const USER_AGENT_INSTRUCTION_TARGETS = [
  {kind: 'block', label: 'codex user instructions', path: '~/.codex/AGENTS.md'},
  {kind: 'block', label: 'claude user instructions', path: '~/.claude/CLAUDE.md'},
  {kind: 'block', label: 'cursor user rule', path: '~/.cursor/rules/threadnote.md'},
  {
    kind: 'file',
    label: 'copilot user instructions',
    path: '~/.copilot/instructions/threadnote.instructions.md',
  },
] as const;

export const CLAUDE_SETTINGS_PATH = '~/.claude/settings.json';
export const THREADNOTE_HOOK_MARKER = '_threadnote';
export const THREADNOTE_HOOK_MARKER_VALUE = 'managed';
export const HOOK_PRE_COMPACT_COMMAND = 'threadnote pre-compact-hook';
export const HOOK_SESSION_START_COMMAND = 'threadnote session-start-hook';
export const HOOK_AUTO_PRECOMPACT_TOPIC = 'auto-precompact';
export const DEFAULT_SEED_PATTERNS = [
  'AGENTS.md',
  'CLAUDE.md',
  'README.md',
  'CONTRIBUTING.md',
  '.github/AGENTS.md',
  '.github/CLAUDE.md',
  '.github/pull_request_template.md',
  '.github/PULL_REQUEST_TEMPLATE.md',
  '.github/PULL_REQUEST_TEMPLATE/*.md',
  '.claude/commands/*.md',
  '.claude/skills/**/SKILL.md',
  '.claude/**/*.md',
  '.agents/**/*.md',
  'docs/**/*.md',
] as const;
