export const DEFAULT_HOST = '127.0.0.1';
export const DEFAULT_PORT = 1933;
export const DEFAULT_OPENVIKING_VERSION = '0.4.10';
// CPython minor the OpenViking tool is pinned to. openviking[local-embed] pulls
// in llama-cpp-python, whose prebuilt wheels (PyPI is sdist-only; wheels live on
// the abetlen community index) top out at 3.12 as of 2026. On newer interpreters
// (3.13/3.14) there is no wheel, so install falls back to a 10-20 min, memory-
// heavy CMake/C++ build that can be OOM-killed or trip command timeouts. Pinning
// the tool to this version keeps installs fast and reliable. Bump when upstream
// ships wheels for a newer minor (abetlen/llama-cpp-python#2103, #2136).
export const OPENVIKING_TOOL_PYTHON = '3.12';
export const DEFAULT_ACCOUNT = 'local';
export const DEFAULT_AGENT_ID = 'threadnote';
export const OPENVIKING_PACKAGE_NAME = 'openviking[local-embed]';
export const OPENVIKING_SERVER_COMMAND = 'openviking-server';
export const OPENVIKING_MCP_NAME = 'threadnote';
export const PYTHON_SYSTEM_CERTS_MODULE = 'pip_system_certs';
export const PYTHON_SYSTEM_CERTS_PACKAGE = 'pip-system-certs';
export const LAUNCHD_LABEL = 'io.threadnote.openviking';
export const MAX_SECRET_MATCHES_TO_PRINT = 5;
export const START_HEALTH_POLL_INTERVAL_MS = 500;
// Fresh OpenViking starts can spend just over 15s warming local embedding/runtime
// dependencies before the HTTP session manager is ready.
export const START_HEALTH_TIMEOUT_MS = 60_000;
export const SHIM_MARKER = 'Generated by threadnote';
export const USER_INSTRUCTIONS_START_MARKER = '<!-- BEGIN THREADNOTE USER INSTRUCTIONS -->';
export const USER_INSTRUCTIONS_END_MARKER = '<!-- END THREADNOTE USER INSTRUCTIONS -->';
export const USER_MANIFEST_NAME = 'seed-manifest.yaml';
export const SEED_STATE_FILE = 'seed-state.json';
// Opt-in: minutes between OpenViking auto-refreshes of seeded repo docs. Unset
// (the default) leaves watches off, so seeded content only refreshes on the
// next `threadnote seed`/`repair` — which re-runs Threadnote's secret scan.
export const SEED_WATCH_INTERVAL_ENV = 'THREADNOTE_SEED_WATCH_INTERVAL';
export const USER_AGENT_INSTRUCTION_TARGETS = [
  {kind: 'block', label: 'codex user instructions', path: '~/.codex/AGENTS.md'},
  {kind: 'block', label: 'claude user instructions', path: '~/.claude/CLAUDE.md'},
  {kind: 'block', label: 'cursor user rule', path: '~/.cursor/rules/threadnote.md'},
  {
    kind: 'file',
    label: 'copilot user instructions',
    path: '~/.copilot/instructions/threadnote.instructions.md',
  },
] as const;

export const CLAUDE_SETTINGS_PATH = '~/.claude/settings.json';
export const THREADNOTE_HOOK_MARKER = '_threadnote';
export const THREADNOTE_HOOK_MARKER_VALUE = 'managed';
export const HOOK_PRE_COMPACT_COMMAND = 'threadnote pre-compact-hook';
export const HOOK_SESSION_START_COMMAND = 'threadnote session-start-hook';
export const HOOK_AUTO_PRECOMPACT_TOPIC = 'auto-precompact';
export const DEFAULT_SEED_PATTERNS = [
  'AGENTS.md',
  'CLAUDE.md',
  'README.md',
  'CONTRIBUTING.md',
  '.github/AGENTS.md',
  '.github/CLAUDE.md',
  '.github/pull_request_template.md',
  '.github/PULL_REQUEST_TEMPLATE.md',
  '.github/PULL_REQUEST_TEMPLATE/*.md',
  '.claude/commands/*.md',
  '.claude/skills/**/SKILL.md',
  '.claude/**/*.md',
  '.agents/**/*.md',
  'docs/**/*.md',
] as const;
